/*
 * $RCSfile: DisplayTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 */
package com.skin.finder.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.skin.finder.config.ConfigFactory;


/**
 * <p>Title: DisplayTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class DisplayTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final DisplayTemplate instance = new DisplayTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();


    String path = (String)(request.getAttribute("path"));
    String theme = (String)(request.getAttribute("theme"));
    String type = (String)(request.getAttribute("type"));
    String encoding = (String)(request.getAttribute("encoding"));
    Long start = (Long)(request.getAttribute("start"));

    if(path == null || (path = path.trim()).length() <= 1) {
        path = "/";
    }

    if(theme == null || (theme = theme.trim()).length() < 1) {
        theme = "Default";
    }

    if(type == null || (type = type.trim()).length() < 1) {
        type = "";
    }

    if(encoding == null || (encoding = encoding.trim()).length() < 1) {
        encoding = "utf-8";
    }

    if(start == null) {
        start = Long.valueOf(0);
    }
    request.setAttribute("path", path);

        out.write(_jsp_string_3, 0, _jsp_string_3.length);
        out.write(_jsp_string_4, 0, _jsp_string_4.length);
        out.write(_jsp_string_5, 0, _jsp_string_5.length);
        out.write(_jsp_string_6, 0, _jsp_string_6.length);
        out.write(_jsp_string_7, 0, _jsp_string_7.length);
        out.write(_jsp_string_8, 0, _jsp_string_8.length);
        this.write(out, request.getAttribute("theme"));
        out.write(_jsp_string_10, 0, _jsp_string_10.length);
        this.write(out, request.getAttribute("theme"));
        out.write(_jsp_string_12, 0, _jsp_string_12.length);
        out.write(_jsp_string_13, 0, _jsp_string_13.length);
        out.write(_jsp_string_14, 0, _jsp_string_14.length);
        out.write(_jsp_string_15, 0, _jsp_string_15.length);
        out.write(_jsp_string_16, 0, _jsp_string_16.length);
        out.write(_jsp_string_17, 0, _jsp_string_17.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_string_19, 0, _jsp_string_19.length);
        this.write(out, request.getAttribute("host"));
        out.write(_jsp_string_21, 0, _jsp_string_21.length);
        this.write(out, request.getAttribute("workspace"));
        out.write(_jsp_string_23, 0, _jsp_string_23.length);
        this.write(out, request.getAttribute("path"));
        out.write(_jsp_string_25, 0, _jsp_string_25.length);
        out.write(_jsp_string_26, 0, _jsp_string_26.length);
        out.write(_jsp_string_27, 0, _jsp_string_27.length);
        out.write(_jsp_string_28, 0, _jsp_string_28.length);
        out.write(_jsp_string_29, 0, _jsp_string_29.length);
        this.write(out, request.getAttribute("path"));
        out.write(_jsp_string_31, 0, _jsp_string_31.length);
        out.write(_jsp_string_32, 0, _jsp_string_32.length);
        this.write(out, (theme));
        out.write(_jsp_string_34, 0, _jsp_string_34.length);
        this.write(out, (type));
        out.write(_jsp_string_36, 0, _jsp_string_36.length);
        this.write(out, (encoding));
        out.write(_jsp_string_38, 0, _jsp_string_38.length);
        this.write(out, request.getAttribute("requestURI"));
        out.write(_jsp_string_40, 0, _jsp_string_40.length);
        out.write(_jsp_string_41, 0, _jsp_string_41.length);

    if(start > 0L) {

        out.write(_jsp_string_43, 0, _jsp_string_43.length);
        out.write(_jsp_string_44, 0, _jsp_string_44.length);
        this.write(out, request.getAttribute("requestURI"));
        out.write(_jsp_string_46, 0, _jsp_string_46.length);
        this.write(out, request.getAttribute("workspace"));
        out.write(_jsp_string_48, 0, _jsp_string_48.length);
        this.write(out, request.getAttribute("path"));
        out.write(_jsp_string_50, 0, _jsp_string_50.length);
        this.write(out, request.getAttribute("start"));
        out.write(_jsp_string_52, 0, _jsp_string_52.length);
        this.write(out, request.getAttribute("end"));
        out.write(_jsp_string_54, 0, _jsp_string_54.length);
        this.write(out, request.getAttribute("length"));
        out.write(_jsp_string_56, 0, _jsp_string_56.length);

    }

        out.write(_jsp_string_58, 0, _jsp_string_58.length);
        this.write(out, request.getAttribute("type"));
        out.write(_jsp_string_60, 0, _jsp_string_60.length);
        this.write(out, request.getAttribute("content"));
        out.write(_jsp_string_62, 0, _jsp_string_62.length);
        out.write(_jsp_string_63, 0, _jsp_string_63.length);
this.write(out, ConfigFactory.getAccessCode(), false);
        out.write(_jsp_string_65, 0, _jsp_string_65.length);

        out.flush();
    }

    protected static final byte[] _jsp_string_3 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_string_4 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_string_5 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>Finder - Powered by Finder</title>\r\n");
    protected static final byte[] _jsp_string_6 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_string_7 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/finder/css/finder.css\"/>\r\n");
    protected static final byte[] _jsp_string_8 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/sh/style/shCore");
    protected static final byte[] _jsp_string_10 = b(".css\"/>\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/sh/style/shTheme");
    protected static final byte[] _jsp_string_12 = b(".css\"/>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.7.2.min.js\"></script>\r\n");
    protected static final byte[] _jsp_string_13 = b("<script type=\"text/javascript\" src=\"?action=res&path=/sh/shCore.js\"></script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/sh/shAutoloader.js\"></script>\r\n");
    protected static final byte[] _jsp_string_14 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/widget.js\"></script>\r\n");
    protected static final byte[] _jsp_string_15 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/finder.js\"></script>\r\n");
    protected static final byte[] _jsp_string_16 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/display.js\"></script>\r\n");
    protected static final byte[] _jsp_string_17 = b("</head>\r\n<body style=\"overflow: hidden;\" page=\"display\" contextPath=\"");
    protected static final byte[] _jsp_string_19 = b("\" host=\"");
    protected static final byte[] _jsp_string_21 = b("\" workspace=\"");
    protected static final byte[] _jsp_string_23 = b("\" path=\"");
    protected static final byte[] _jsp_string_25 = b("\">\r\n<div class=\"finder\" style=\"min-width: 988px;\">\r\n    <div class=\"menu-bar\">\r\n");
    protected static final byte[] _jsp_string_26 = b("        <div style=\"float: left; width: 80px;\">\r\n            <a class=\"button\" href=\"javascript:void(0)\" title=\"后退\"><span class=\"back\"></span></a>\r\n");
    protected static final byte[] _jsp_string_27 = b("            <a class=\"button\" href=\"javascript:void(0)\" title=\"刷新\"><span class=\"refresh\"></span></a>\r\n");
    protected static final byte[] _jsp_string_28 = b("        </div>\r\n        <div style=\"float: left; height: 28px; position: relative;\">\r\n");
    protected static final byte[] _jsp_string_29 = b("            <div style=\"float: left;\"><input id=\"address\" type=\"text\" class=\"address\" autocomplete=\"off\" file=\"true\" value=\"");
    protected static final byte[] _jsp_string_31 = b("\"/></div>\r\n            <div id=\"finder-suggest\" class=\"list suggest\"></div>\r\n            <span class=\"label\">theme:</span>\r\n");
    protected static final byte[] _jsp_string_32 = b("            <select id=\"uiThemeOption\" selected-value=\"");
    protected static final byte[] _jsp_string_34 = b("\"></select>\r\n\r\n            <span class=\"label\">type:</span>\r\n            <select id=\"uiTypeOption\" selected-value=\"");
    protected static final byte[] _jsp_string_36 = b("\"></select>\r\n\r\n            <span class=\"label\">encoding:</span>\r\n            <select id=\"uiEncodingOption\" selected-value=\"");
    protected static final byte[] _jsp_string_38 = b("\"></select>\r\n        </div>\r\n        <div style=\"float: right; width: 40px;\">\r\n            <a class=\"button\" href=\"");
    protected static final byte[] _jsp_string_40 = b("?action=finder.help\" title=\"帮助\" target=\"_blank\"><span class=\"help\"></span></a>\r\n");
    protected static final byte[] _jsp_string_41 = b("        </div>\r\n    </div>\r\n</div>\r\n");
    protected static final byte[] _jsp_string_43 = b("<div style=\"padding-left: 4px; height: 28px; line-height: 28px; background-color: #efefef; font-size: 12px;\">\r\n");
    protected static final byte[] _jsp_string_44 = b("    文件较大，只显示部分数据。要查看全部数据请使用 <a href=\"");
    protected static final byte[] _jsp_string_46 = b("?action=finder.less&workspace=");
    protected static final byte[] _jsp_string_48 = b("&path=");
    protected static final byte[] _jsp_string_50 = b("\" style=\"color: #ff0000;\">less</a> 打开。\r\n    [");
    protected static final byte[] _jsp_string_52 = b(" - ");
    protected static final byte[] _jsp_string_54 = b("/");
    protected static final byte[] _jsp_string_56 = b("]\r\n</div>\r\n");
    protected static final byte[] _jsp_string_58 = b("<div id=\"content\" file-type=\"");
    protected static final byte[] _jsp_string_60 = b("\" style=\"display: none;\"><pre class=\"brush: bash;\">");
    protected static final byte[] _jsp_string_62 = b("</pre></div>\r\n<div id=\"loading\" class=\"widget-mask\" style=\"display: block;\" contextmenu=\"false\"><div class=\"loading\"><img src=\"?action=res&path=/finder/images/loading.gif\"/></div></div>\r\n");
    protected static final byte[] _jsp_string_63 = b("<div style=\"display: none;\">");
    protected static final byte[] _jsp_string_65 = b("</div>\r\n</body>\r\n</html>");

}
