/*
 * $RCSfile: IndexTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 */
package com.skin.finder.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.skin.finder.config.ConfigFactory;
import com.skin.finder.i18n.I18N;
import com.skin.finder.i18n.LocalizationContext;


/**
 * <p>Title: IndexTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class IndexTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final IndexTemplate instance = new IndexTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();


    LocalizationContext i18n = I18N.getBundle(request);

        out.write(_jsp_string_5, 0, _jsp_string_5.length);
        out.write(_jsp_string_6, 0, _jsp_string_6.length);
        out.write(_jsp_string_7, 0, _jsp_string_7.length);
        out.write(_jsp_string_8, 0, _jsp_string_8.length);
        out.write(_jsp_string_9, 0, _jsp_string_9.length);
        out.write(_jsp_string_10, 0, _jsp_string_10.length);
        out.write(_jsp_string_11, 0, _jsp_string_11.length);
        out.write(_jsp_string_12, 0, _jsp_string_12.length);
        out.write(_jsp_string_13, 0, _jsp_string_13.length);
        out.write(_jsp_string_14, 0, _jsp_string_14.length);
        out.write(_jsp_string_15, 0, _jsp_string_15.length);
        out.write(_jsp_string_16, 0, _jsp_string_16.length);
        this.write(out, request.getAttribute("localIp"));
        out.write(_jsp_string_18, 0, _jsp_string_18.length);
        this.write(out, request.getAttribute("userName"));
        out.write(_jsp_string_20, 0, _jsp_string_20.length);
        out.write(_jsp_string_21, 0, _jsp_string_21.length);
        out.write(_jsp_string_22, 0, _jsp_string_22.length);
        out.write(_jsp_string_23, 0, _jsp_string_23.length);
        this.write(out, (i18n.format("finder.index.home")));
        out.write(_jsp_string_25, 0, _jsp_string_25.length);
        this.write(out, (i18n.format("finder.index.setting")));
        out.write(_jsp_string_27, 0, _jsp_string_27.length);
        this.write(out, (i18n.format("finder.index.help")));
        out.write(_jsp_string_29, 0, _jsp_string_29.length);
        this.write(out, (i18n.format("finder.index.logout")));
        out.write(_jsp_string_31, 0, _jsp_string_31.length);
        out.write(_jsp_string_32, 0, _jsp_string_32.length);
        this.write(out, request.getAttribute("requestURI"));
        out.write(_jsp_string_34, 0, _jsp_string_34.length);
        this.write(out, (i18n.format("finder.index.home")));
        out.write(_jsp_string_36, 0, _jsp_string_36.length);
        out.write(_jsp_string_37, 0, _jsp_string_37.length);
        out.write(_jsp_string_38, 0, _jsp_string_38.length);
        this.write(out, request.getAttribute("requestURI"));
        out.write(_jsp_string_40, 0, _jsp_string_40.length);
        out.write(_jsp_string_41, 0, _jsp_string_41.length);
        out.write(_jsp_string_42, 0, _jsp_string_42.length);
        this.write(out, request.getAttribute("requestURI"));
        out.write(_jsp_string_44, 0, _jsp_string_44.length);
        out.write(_jsp_string_45, 0, _jsp_string_45.length);
        out.write(_jsp_string_46, 0, _jsp_string_46.length);
        this.write(out, request.getAttribute("version"));
        out.write(_jsp_string_48, 0, _jsp_string_48.length);
        out.write(_jsp_string_49, 0, _jsp_string_49.length);
        this.write(out, request.getAttribute("remoteIp"));
        out.write(_jsp_string_51, 0, _jsp_string_51.length);
        this.write(out, request.getAttribute("userName"));
        out.write(_jsp_string_53, 0, _jsp_string_53.length);
        this.write(out, (i18n.format("finder.index.welcome")));
        out.write(_jsp_string_55, 0, _jsp_string_55.length);

    if(Boolean.TRUE.equals(request.getAttribute("hasNewVersion"))) {

        out.write(_jsp_string_57, 0, _jsp_string_57.length);
        this.write(out, request.getAttribute("newVersion"));
        out.write(_jsp_string_59, 0, _jsp_string_59.length);
        this.write(out, request.getAttribute("downloadUrl"));
        out.write(_jsp_string_61, 0, _jsp_string_61.length);
        this.write(out, request.getAttribute("newVersion"));
        out.write(_jsp_string_63, 0, _jsp_string_63.length);

    }

        out.write(_jsp_string_65, 0, _jsp_string_65.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_string_67, 0, _jsp_string_67.length);
        this.write(out, request.getAttribute("admin"));
        out.write(_jsp_string_69, 0, _jsp_string_69.length);
        this.write(out, (ConfigFactory.getNavBar()));
        out.write(_jsp_string_71, 0, _jsp_string_71.length);
this.write(out, ConfigFactory.getAccessCode(), false);
        out.write(_jsp_string_73, 0, _jsp_string_73.length);

        out.flush();
    }

    protected static final byte[] _jsp_string_5 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_string_6 = b("<title>Finder - Powered by Finder</title>\r\n<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_string_7 = b("<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Expires\" content=\"0\"/>\r\n");
    protected static final byte[] _jsp_string_8 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_string_9 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/finder/css/frame.css\"/>\r\n");
    protected static final byte[] _jsp_string_10 = b("<script type=\"text/javascript\">\r\n<!--\r\n(function() {\r\n    if(window.parent != window) {\r\n");
    protected static final byte[] _jsp_string_11 = b("        window.top.location.href = window.location.href;\r\n        return;\r\n    }\r\n");
    protected static final byte[] _jsp_string_12 = b("})();\r\n//-->\r\n</script>\r\n<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.7.2.min.js\"></script>\r\n");
    protected static final byte[] _jsp_string_13 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/widget.js\"></script>\r\n");
    protected static final byte[] _jsp_string_14 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/fileupload.js\"></script>\r\n");
    protected static final byte[] _jsp_string_15 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/index.js\"></script>\r\n");
    protected static final byte[] _jsp_string_16 = b("</head>\r\n<body localIp=\"");
    protected static final byte[] _jsp_string_18 = b("\" userName=\"");
    protected static final byte[] _jsp_string_20 = b("\">\r\n<div class=\"apptop\">\r\n    <a href=\"http://www.finderweb.net\" target=\"_blank\"><div class=\"logo\" title=\"http://www.finderweb.net\"></div></a>\r\n");
    protected static final byte[] _jsp_string_21 = b("    <div style=\"margin-left: 300px; height: 60px;\">\r\n        <div style=\"height: 28px;\">\r\n");
    protected static final byte[] _jsp_string_22 = b("            <div id=\"tools-menu\" class=\"tools-menu\" style=\"display: none;\">\r\n                <ul>\r\n");
    protected static final byte[] _jsp_string_23 = b("                    <li id=\"tools-home\" class=\"icon-01\" onclick=\"App.home();\">");
    protected static final byte[] _jsp_string_25 = b("</li>\r\n                    <li id=\"tools-setting\" class=\"icon-07\" onclick=\"App.setting();\">");
    protected static final byte[] _jsp_string_27 = b("</li>\r\n                    <li id=\"tools-help\" class=\"icon-08\" onclick=\"App.help();\">");
    protected static final byte[] _jsp_string_29 = b("</li>\r\n                    <li id=\"tools-logout\" class=\"icon-09\" onclick=\"App.logout();\">");
    protected static final byte[] _jsp_string_31 = b("</li>\r\n                </ul>\r\n            </div>\r\n        </div>\r\n        <div class=\"menu-bar\">\r\n");
    protected static final byte[] _jsp_string_32 = b("            <ul>\r\n                <!-- li class=\"active\" onclick=\"window.location.href='");
    protected static final byte[] _jsp_string_34 = b("';\">");
    protected static final byte[] _jsp_string_36 = b("</li -->\r\n            </ul>\r\n        </div>\r\n    </div>\r\n</div>\r\n<div id=\"viewPanel\">\r\n");
    protected static final byte[] _jsp_string_37 = b("    <div id=\"leftPanel\" class=\"left-panel\"><iframe id=\"leftFrame\" name=\"leftFrame\" class=\"left-frame\"\r\n");
    protected static final byte[] _jsp_string_38 = b("        src=\"");
    protected static final byte[] _jsp_string_40 = b("?action=finder.tree\" frameborder=\"0\" scrolling=\"no\" marginwidth=\"0\" marginheight=\"0\"></iframe></div>\r\n");
    protected static final byte[] _jsp_string_41 = b("\r\n    <div id=\"mainPanel\" class=\"main-panel\"><iframe id=\"mainFrame\" name=\"mainFrame\" class=\"main-frame\"\r\n");
    protected static final byte[] _jsp_string_42 = b("        src=\"");
    protected static final byte[] _jsp_string_44 = b("?action=finder.tabpanel\" frameborder=\"0\" scrolling=\"auto\" marginwidth=\"0\" marginheight=\"0\"></iframe></div>\r\n");
    protected static final byte[] _jsp_string_45 = b("</div>\r\n<div id=\"statusBar\" class=\"status-bar hide\">\r\n    <div id=\"_task_bar\" class=\"widget-task-bar\"></div>\r\n");
    protected static final byte[] _jsp_string_46 = b("    <div class=\"footer\">\r\n        <span class=\"copyright\">Powered by Finder v");
    protected static final byte[] _jsp_string_48 = b(" | Copyright © <a href=\"http://www.finderweb.net/\" draggable=\"false\" target=\"_blank\">www.finderweb.net</a> All rights reserved.</span>\r\n");
    protected static final byte[] _jsp_string_49 = b("        <img style=\"margin-top: -2px; margin-right: 4px;\" src=\"?action=res&path=/finder/images/sound.gif\" title=\"");
    protected static final byte[] _jsp_string_51 = b(": ");
    protected static final byte[] _jsp_string_53 = b("\"/>");
    protected static final byte[] _jsp_string_55 = b("    </div>\r\n</div>\r\n");
    protected static final byte[] _jsp_string_57 = b("<div id=\"upgrade-tips\" class=\"upgrade-tips\">New Upgrade ");
    protected static final byte[] _jsp_string_59 = b("！<a href=\"");
    protected static final byte[] _jsp_string_61 = b("\" title=\"");
    protected static final byte[] _jsp_string_63 = b("\" target=\"_blank\">Click for download.</a>\r\n</div>\r\n");
    protected static final byte[] _jsp_string_65 = b("<div id=\"pageContext\" style=\"display: none;\" contextPath=\"");
    protected static final byte[] _jsp_string_67 = b("\" admin=\"");
    protected static final byte[] _jsp_string_69 = b("\" nav-bar=\"");
    protected static final byte[] _jsp_string_71 = b("\"></div>\r\n<div style=\"display: none;\">");
    protected static final byte[] _jsp_string_73 = b("</div>\r\n</body>\r\n</html>\r\n");

}
