/*
 * $RCSfile: LoginTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 */
package com.skin.finder.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.skin.finder.config.ConfigFactory;


/**
 * <p>Title: LoginTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class LoginTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final LoginTemplate instance = new LoginTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_string_2, 0, _jsp_string_2.length);
        out.write(_jsp_string_3, 0, _jsp_string_3.length);
        out.write(_jsp_string_4, 0, _jsp_string_4.length);
        out.write(_jsp_string_5, 0, _jsp_string_5.length);
        out.write(_jsp_string_6, 0, _jsp_string_6.length);
        out.write(_jsp_string_7, 0, _jsp_string_7.length);
        out.write(_jsp_string_8, 0, _jsp_string_8.length);
        out.write(_jsp_string_9, 0, _jsp_string_9.length);
        out.write(_jsp_string_10, 0, _jsp_string_10.length);
        out.write(_jsp_string_11, 0, _jsp_string_11.length);
        out.write(_jsp_string_12, 0, _jsp_string_12.length);
        out.write(_jsp_string_13, 0, _jsp_string_13.length);
        out.write(_jsp_string_14, 0, _jsp_string_14.length);
        out.write(_jsp_string_15, 0, _jsp_string_15.length);
        out.write(_jsp_string_16, 0, _jsp_string_16.length);
        out.write(_jsp_string_17, 0, _jsp_string_17.length);
        out.write(_jsp_string_18, 0, _jsp_string_18.length);
        out.write(_jsp_string_19, 0, _jsp_string_19.length);
        out.write(_jsp_string_20, 0, _jsp_string_20.length);
        out.write(_jsp_string_21, 0, _jsp_string_21.length);
        out.write(_jsp_string_22, 0, _jsp_string_22.length);
        out.write(_jsp_string_23, 0, _jsp_string_23.length);
        out.write(_jsp_string_24, 0, _jsp_string_24.length);
        out.write(_jsp_string_25, 0, _jsp_string_25.length);
        out.write(_jsp_string_26, 0, _jsp_string_26.length);
        out.write(_jsp_string_27, 0, _jsp_string_27.length);
        out.write(_jsp_string_28, 0, _jsp_string_28.length);
        out.write(_jsp_string_29, 0, _jsp_string_29.length);
        out.write(_jsp_string_30, 0, _jsp_string_30.length);
        this.write(out, (ConfigFactory.getDemoUserName()));
        out.write(_jsp_string_32, 0, _jsp_string_32.length);
        this.write(out, (ConfigFactory.getDemoPassword()));
        out.write(_jsp_string_34, 0, _jsp_string_34.length);
        out.write(_jsp_string_35, 0, _jsp_string_35.length);
this.write(out, ConfigFactory.getAccessCode(), false);
        out.write(_jsp_string_37, 0, _jsp_string_37.length);

        out.flush();
    }

    protected static final byte[] _jsp_string_2 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_string_3 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_string_4 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>Login - Powered by Finder</title>\r\n");
    protected static final byte[] _jsp_string_5 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_string_6 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/finder/css/user.css\"/>\r\n");
    protected static final byte[] _jsp_string_7 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.7.2.min.js\"></script>\r\n");
    protected static final byte[] _jsp_string_8 = b("<script type=\"text/javascript\">\r\n<!--\r\njQuery(function() {\r\n    var getParameter = function(url, name) {\r\n");
    protected static final byte[] _jsp_string_9 = b("        var queryString = url;\r\n        var k = url.indexOf(\"?\");\r\n\r\n        if(k > -1) {\r\n");
    protected static final byte[] _jsp_string_10 = b("            queryString = url.substring(k + 1);\r\n        }\r\n\r\n        var array = queryString.split(\"&\");\r\n");
    protected static final byte[] _jsp_string_11 = b("\r\n        for(var i = 0; i < array.length; i++) {\r\n            var e = array[i];\r\n");
    protected static final byte[] _jsp_string_12 = b("            var j = e.indexOf(\"=\");\r\n\r\n            if(j > -1) {\r\n                var key = e.substring(0, j);\r\n");
    protected static final byte[] _jsp_string_13 = b("\r\n                if(key == name) {\r\n                    return decodeURIComponent(e.substring(j + 1));\r\n");
    protected static final byte[] _jsp_string_14 = b("                }\r\n            }\r\n        }\r\n        return null;\r\n    };\r\n\r\n    jQuery(\"#submit\").click(function() {\r\n");
    protected static final byte[] _jsp_string_15 = b("        var userName = jQuery.trim(jQuery(\"#s1\").val());\r\n        var password = jQuery.trim(jQuery(\"#s2\").val());\r\n");
    protected static final byte[] _jsp_string_16 = b("        var params = \"userName=\" + encodeURIComponent(userName) + \"&password=\" + encodeURIComponent(password);\r\n");
    protected static final byte[] _jsp_string_17 = b("        var requestURI = window.location.pathname;\r\n\r\n        jQuery.ajax({\r\n            type: \"post\",\r\n");
    protected static final byte[] _jsp_string_18 = b("            url: requestURI + \"?action=finder.login\",\r\n            dataType: \"json\",\r\n");
    protected static final byte[] _jsp_string_19 = b("            data: params,\r\n            error: function(req, status, error) {\r\n                alert(\"系统错误，请稍后再试！\");\r\n");
    protected static final byte[] _jsp_string_20 = b("            },\r\n            success: function(result) {\r\n                if(result.status == 200) {\r\n");
    protected static final byte[] _jsp_string_21 = b("                    var redirect = getParameter(window.location.search, \"redirect\");\r\n");
    protected static final byte[] _jsp_string_22 = b("\r\n                    if(redirect != null) {\r\n                        window.location.href = redirect;\r\n");
    protected static final byte[] _jsp_string_23 = b("                    }\r\n                    else {\r\n                        window.location.href = requestURI;\r\n");
    protected static final byte[] _jsp_string_24 = b("                    }\r\n                }\r\n                else {\r\n                    alert(result.message);\r\n");
    protected static final byte[] _jsp_string_25 = b("                }\r\n            }\r\n        });\r\n    });\r\n});\r\n//-->\r\n</script>\r\n</head>\r\n");
    protected static final byte[] _jsp_string_26 = b("<body style=\"background: url(?action=res&path=/finder/images/7a4f.jpg) center center / cover no-repeat fixed;\">\r\n");
    protected static final byte[] _jsp_string_27 = b("<div class=\"apptop\">\r\n    <a href=\"http://www.finderweb.net\" target=\"_blank\"><div class=\"logo\" title=\"http://www.finderweb.net\"></div></a>\r\n");
    protected static final byte[] _jsp_string_28 = b("    <div style=\"margin-left: 300px; height: 60px;\">\r\n        <div style=\"height: 28px;\"></div>\r\n");
    protected static final byte[] _jsp_string_29 = b("        <div class=\"menu-bar\"></div>\r\n    </div>\r\n</div>\r\n<div class=\"wrap\">\r\n    <div class=\"login-container\">\r\n");
    protected static final byte[] _jsp_string_30 = b("        <div class=\"login-panel\">\r\n            <h2>用户登录</h2>\r\n            <div class=\"row\"><input id=\"s1\" type=\"text\" class=\"text\" spellcheck=\"false\" placeholder=\"UserName\" value=\"");
    protected static final byte[] _jsp_string_32 = b("\"/></div>\r\n            <div class=\"row\"><input id=\"s2\" type=\"password\" class=\"text\" placeholder=\"Password\" value=\"");
    protected static final byte[] _jsp_string_34 = b("\"/></div>\r\n            <div class=\"row\"><input id=\"submit\" type=\"button\" class=\"button\" value=\"登录\"/></div>\r\n");
    protected static final byte[] _jsp_string_35 = b("        </div>\r\n    </div>\r\n</div>\r\n<div style=\"display: none;\">");
    protected static final byte[] _jsp_string_37 = b("</div>\r\n<!-- http://www.finderweb.net -->\r\n</body>\r\n</html>\r\n");

}
