/*
 * $RCSfile: PasswordTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 */
package com.skin.finder.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;



/**
 * <p>Title: PasswordTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class PasswordTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final PasswordTemplate instance = new PasswordTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_string_1, 0, _jsp_string_1.length);
        out.write(_jsp_string_2, 0, _jsp_string_2.length);
        out.write(_jsp_string_3, 0, _jsp_string_3.length);
        out.write(_jsp_string_4, 0, _jsp_string_4.length);
        out.write(_jsp_string_5, 0, _jsp_string_5.length);
        out.write(_jsp_string_6, 0, _jsp_string_6.length);
        out.write(_jsp_string_7, 0, _jsp_string_7.length);
        out.write(_jsp_string_8, 0, _jsp_string_8.length);
        out.write(_jsp_string_9, 0, _jsp_string_9.length);
        out.write(_jsp_string_10, 0, _jsp_string_10.length);
        out.write(_jsp_string_11, 0, _jsp_string_11.length);
        out.write(_jsp_string_12, 0, _jsp_string_12.length);
        out.write(_jsp_string_13, 0, _jsp_string_13.length);
        out.write(_jsp_string_14, 0, _jsp_string_14.length);
        out.write(_jsp_string_15, 0, _jsp_string_15.length);
        out.write(_jsp_string_16, 0, _jsp_string_16.length);
        out.write(_jsp_string_17, 0, _jsp_string_17.length);
        out.write(_jsp_string_18, 0, _jsp_string_18.length);
        out.write(_jsp_string_19, 0, _jsp_string_19.length);
        out.write(_jsp_string_20, 0, _jsp_string_20.length);
        out.write(_jsp_string_21, 0, _jsp_string_21.length);

        out.flush();
    }

    protected static final byte[] _jsp_string_1 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_string_2 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_string_3 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>Finder - Powered by Finder</title>\r\n");
    protected static final byte[] _jsp_string_4 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_string_5 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/finder/css/user.css\"/>\r\n");
    protected static final byte[] _jsp_string_6 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.7.2.min.js\"></script>\r\n");
    protected static final byte[] _jsp_string_7 = b("<script type=\"text/javascript\">\r\n<!--\r\njQuery(function() {\r\n    jQuery(\"#submit\").click(function() {\r\n");
    protected static final byte[] _jsp_string_8 = b("        var userName = jQuery.trim(jQuery(\"#s1\").val());\r\n        var oldPassword = jQuery.trim(jQuery(\"#s1\").val());\r\n");
    protected static final byte[] _jsp_string_9 = b("        var newPassword = jQuery.trim(jQuery(\"#s2\").val());\r\n        var params = \"userName=\" + encodeURIComponent(userName) + \"&oldPassword=\" + encodeURIComponent(oldPassword) +  + \"&newPassword=\" + encodeURIComponent(newPassword);\r\n");
    protected static final byte[] _jsp_string_10 = b("        var requestURI = window.location.pathname;\r\n\r\n        jQuery.ajax({\r\n            type: \"post\",\r\n");
    protected static final byte[] _jsp_string_11 = b("            url: requestURI + \"?action=user.password.update\",\r\n            dataType: \"json\",\r\n");
    protected static final byte[] _jsp_string_12 = b("            data: params,\r\n            error: function(req, status, error) {\r\n                alert(\"系统错误，请稍后再试！\");\r\n");
    protected static final byte[] _jsp_string_13 = b("            },\r\n            success: function(result) {\r\n                if(result.status == 200) {\r\n");
    protected static final byte[] _jsp_string_14 = b("                    alert(\"添加用户成功！\");\r\n                    window.location.reload();\r\n");
    protected static final byte[] _jsp_string_15 = b("                }\r\n                else {\r\n                    alert(result.message);\r\n");
    protected static final byte[] _jsp_string_16 = b("                }\r\n            }\r\n        });\r\n    });\r\n});\r\n//-->\r\n</script>\r\n</head>\r\n");
    protected static final byte[] _jsp_string_17 = b("<body>\r\n<div class=\"wrap\">\r\n    <div class=\"login-container\">\r\n        <h3>修改密码</h3>\r\n");
    protected static final byte[] _jsp_string_18 = b("        <div class=\"login-panel\">\r\n            <div class=\"row\"><input id=\"s1\" type=\"oldPassword\" class=\"text\" placeholder=\"Old Password\" value=\"\"/></div>\r\n");
    protected static final byte[] _jsp_string_19 = b("            <div class=\"row\"><input id=\"s2\" type=\"newPassword\" class=\"text\" placeholder=\"New Password\" value=\"\"/></div>\r\n");
    protected static final byte[] _jsp_string_20 = b("            <div class=\"row\"><input id=\"submit\" type=\"button\" class=\"button\" value=\"提交\"/></div>\r\n");
    protected static final byte[] _jsp_string_21 = b("        </div>\r\n    </div>\r\n</div>\r\n</body>\r\n</html>");

}
