/*
 * $RCSfile: SettingTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 */
package com.skin.finder.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;



/**
 * <p>Title: SettingTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class SettingTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final SettingTemplate instance = new SettingTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_string_0, 0, _jsp_string_0.length);
        out.write(_jsp_string_1, 0, _jsp_string_1.length);
        out.write(_jsp_string_2, 0, _jsp_string_2.length);
        out.write(_jsp_string_3, 0, _jsp_string_3.length);
        out.write(_jsp_string_4, 0, _jsp_string_4.length);
        out.write(_jsp_string_5, 0, _jsp_string_5.length);
        out.write(_jsp_string_6, 0, _jsp_string_6.length);
        out.write(_jsp_string_7, 0, _jsp_string_7.length);
        out.write(_jsp_string_8, 0, _jsp_string_8.length);
        out.write(_jsp_string_9, 0, _jsp_string_9.length);
        out.write(_jsp_string_10, 0, _jsp_string_10.length);
        out.write(_jsp_string_11, 0, _jsp_string_11.length);
        out.write(_jsp_string_12, 0, _jsp_string_12.length);
        out.write(_jsp_string_13, 0, _jsp_string_13.length);
        out.write(_jsp_string_14, 0, _jsp_string_14.length);
        out.write(_jsp_string_15, 0, _jsp_string_15.length);
        out.write(_jsp_string_16, 0, _jsp_string_16.length);
        out.write(_jsp_string_17, 0, _jsp_string_17.length);
        out.write(_jsp_string_18, 0, _jsp_string_18.length);
        out.write(_jsp_string_19, 0, _jsp_string_19.length);
        out.write(_jsp_string_20, 0, _jsp_string_20.length);
        out.write(_jsp_string_21, 0, _jsp_string_21.length);
        out.write(_jsp_string_22, 0, _jsp_string_22.length);
        out.write(_jsp_string_23, 0, _jsp_string_23.length);
        out.write(_jsp_string_24, 0, _jsp_string_24.length);
        out.write(_jsp_string_25, 0, _jsp_string_25.length);
        out.write(_jsp_string_26, 0, _jsp_string_26.length);
        out.write(_jsp_string_27, 0, _jsp_string_27.length);
        out.write(_jsp_string_28, 0, _jsp_string_28.length);
        out.write(_jsp_string_29, 0, _jsp_string_29.length);
        out.write(_jsp_string_30, 0, _jsp_string_30.length);
        out.write(_jsp_string_31, 0, _jsp_string_31.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_string_33, 0, _jsp_string_33.length);
        this.write(out, request.getAttribute("workspace"));
        out.write(_jsp_string_35, 0, _jsp_string_35.length);
        out.write(_jsp_string_36, 0, _jsp_string_36.length);
        out.write(_jsp_string_37, 0, _jsp_string_37.length);
        out.write(_jsp_string_38, 0, _jsp_string_38.length);
        out.write(_jsp_string_39, 0, _jsp_string_39.length);
        out.write(_jsp_string_40, 0, _jsp_string_40.length);
        out.write(_jsp_string_41, 0, _jsp_string_41.length);
        out.write(_jsp_string_42, 0, _jsp_string_42.length);
        out.write(_jsp_string_43, 0, _jsp_string_43.length);
        out.write(_jsp_string_44, 0, _jsp_string_44.length);
        out.write(_jsp_string_45, 0, _jsp_string_45.length);
        out.write(_jsp_string_46, 0, _jsp_string_46.length);
        out.write(_jsp_string_47, 0, _jsp_string_47.length);
        out.write(_jsp_string_48, 0, _jsp_string_48.length);
        out.write(_jsp_string_49, 0, _jsp_string_49.length);
        out.write(_jsp_string_50, 0, _jsp_string_50.length);
        out.write(_jsp_string_51, 0, _jsp_string_51.length);
        out.write(_jsp_string_52, 0, _jsp_string_52.length);
        out.write(_jsp_string_53, 0, _jsp_string_53.length);
        out.write(_jsp_string_54, 0, _jsp_string_54.length);
        out.write(_jsp_string_55, 0, _jsp_string_55.length);
        out.write(_jsp_string_56, 0, _jsp_string_56.length);
        out.write(_jsp_string_57, 0, _jsp_string_57.length);
        out.write(_jsp_string_58, 0, _jsp_string_58.length);
        out.write(_jsp_string_59, 0, _jsp_string_59.length);
        out.write(_jsp_string_60, 0, _jsp_string_60.length);
        out.write(_jsp_string_61, 0, _jsp_string_61.length);
        out.write(_jsp_string_62, 0, _jsp_string_62.length);
        out.write(_jsp_string_63, 0, _jsp_string_63.length);
        out.write(_jsp_string_64, 0, _jsp_string_64.length);
        out.write(_jsp_string_65, 0, _jsp_string_65.length);
        out.write(_jsp_string_66, 0, _jsp_string_66.length);
        out.write(_jsp_string_67, 0, _jsp_string_67.length);
        out.write(_jsp_string_68, 0, _jsp_string_68.length);
        out.write(_jsp_string_69, 0, _jsp_string_69.length);
        out.write(_jsp_string_70, 0, _jsp_string_70.length);
        out.write(_jsp_string_71, 0, _jsp_string_71.length);
        out.write(_jsp_string_72, 0, _jsp_string_72.length);
        out.write(_jsp_string_73, 0, _jsp_string_73.length);
        out.write(_jsp_string_74, 0, _jsp_string_74.length);
        out.write(_jsp_string_75, 0, _jsp_string_75.length);
        out.write(_jsp_string_76, 0, _jsp_string_76.length);
        out.write(_jsp_string_77, 0, _jsp_string_77.length);
        out.write(_jsp_string_78, 0, _jsp_string_78.length);
        out.write(_jsp_string_79, 0, _jsp_string_79.length);
        out.write(_jsp_string_80, 0, _jsp_string_80.length);

        out.flush();
    }

    protected static final byte[] _jsp_string_0 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_string_1 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_string_2 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>Setting - Powered by Finder</title>\r\n");
    protected static final byte[] _jsp_string_3 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_string_4 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/finder/css/form.css\"/>\r\n");
    protected static final byte[] _jsp_string_5 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.7.2.min.js\"></script>\r\n");
    protected static final byte[] _jsp_string_6 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/charset.js\"></script>\r\n");
    protected static final byte[] _jsp_string_7 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/colorpicker.js\"></script>\r\n");
    protected static final byte[] _jsp_string_8 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/config.js\"></script>\r\n");
    protected static final byte[] _jsp_string_9 = b("<script type=\"text/javascript\">\r\n<!--\r\njQuery(function() {\r\n    var theme = Finder.getConfig(\"global.theme\", \"RDark\");\r\n");
    protected static final byte[] _jsp_string_10 = b("    var charset = Finder.getConfig(\"global.charset\", \"utf-8\");\r\n    var fontFamily = Finder.getConfig(\"less.fontFamily\", \"Lucida Console\");\r\n");
    protected static final byte[] _jsp_string_11 = b("    var fontColor = Finder.getConfig(\"less.fontColor\", \"#999999\");\r\n    var backgroundColor = Finder.getConfig(\"less.backgroundColor\", \"#000000\");\r\n");
    protected static final byte[] _jsp_string_12 = b("    Charset.setup(jQuery(\"select[name=charset]\").get(0), charset);\r\n\r\n    jQuery(\"select[name=theme]\").val(theme);\r\n");
    protected static final byte[] _jsp_string_13 = b("    jQuery(\"select[name=fontFamily]\").val(fontFamily);\r\n    jQuery(\"input[name=fontColor]\").val(fontColor);\r\n");
    protected static final byte[] _jsp_string_14 = b("    jQuery(\"input[name=backgroundColor]\").val(backgroundColor);\r\n\r\n    jQuery(\"input[name=fontColorPicker]\").css(\"backgroundColor\", fontColor);\r\n");
    protected static final byte[] _jsp_string_15 = b("    jQuery(\"input[name=backgroundColorPicker]\").css(\"backgroundColor\", backgroundColor);\r\n");
    protected static final byte[] _jsp_string_16 = b("    jQuery(\"#fontExample\").css(\"fontFamily\", fontFamily);\r\n});\r\n\r\njQuery(function() {\r\n");
    protected static final byte[] _jsp_string_17 = b("    jQuery(\"input.color-picker\").click(function(event) {\r\n        var position = jQuery(this).position();\r\n");
    protected static final byte[] _jsp_string_18 = b("        var x = position.left;\r\n        var y = position.top + jQuery(this).height();\r\n");
    protected static final byte[] _jsp_string_19 = b("        var self = jQuery(this);\r\n\r\n        ColorDialog.open(x, y, function(color) {\r\n");
    protected static final byte[] _jsp_string_20 = b("            self.css(\"backgroundColor\", color);\r\n            self.parent().find(\"input.color-text\").val(color);\r\n");
    protected static final byte[] _jsp_string_21 = b("            ColorDialog.close();\r\n        });\r\n    });\r\n\r\n    jQuery(\"select[name=fontFamily]\").change(function() {\r\n");
    protected static final byte[] _jsp_string_22 = b("        jQuery(\"#fontExample\").css(\"fontFamily\", this.value);\r\n    });\r\n\r\n    jQuery(\"#default-btn\").click(function() {\r\n");
    protected static final byte[] _jsp_string_23 = b("        jQuery(\"select[name=theme]\").val(\"RDark\");\r\n        jQuery(\"select[name=charset]\").val(\"utf-8\");\r\n");
    protected static final byte[] _jsp_string_24 = b("        jQuery(\"select[name=fontFamily]\").val(\"Lucida Console\");\r\n        jQuery(\"input[name=fontColor]\").val(\"#999999\");\r\n");
    protected static final byte[] _jsp_string_25 = b("        jQuery(\"input[name=backgroundColor]\").val(\"#000000\");\r\n    });\r\n\r\n    jQuery(\"#ensure-btn\").click(function() {\r\n");
    protected static final byte[] _jsp_string_26 = b("        var config = {\"global\": {}, \"less\": {}};\r\n        var global = config.global;\r\n");
    protected static final byte[] _jsp_string_27 = b("        var lessConfig = config.less;\r\n\r\n        global.theme = jQuery(\"select[name=theme]\").val();\r\n");
    protected static final byte[] _jsp_string_28 = b("        global.charset = jQuery(\"select[name=charset]\").val();\r\n\r\n        lessConfig.fontFamily = jQuery(\"select[name=fontFamily]\").val();\r\n");
    protected static final byte[] _jsp_string_29 = b("        lessConfig.fontColor = jQuery(\"input[name=fontColor]\").val();\r\n        lessConfig.backgroundColor = jQuery(\"input[name=backgroundColor]\").val();\r\n");
    protected static final byte[] _jsp_string_30 = b("        Finder.setFinderConfig(config);\r\n        window.close();\r\n    });\r\n\r\n    jQuery(\"#cancel-btn\").click(function() {\r\n");
    protected static final byte[] _jsp_string_31 = b("        window.close();\r\n    });\r\n});\r\n//-->\r\n</script>\r\n</head>\r\n<body contextPath=\"");
    protected static final byte[] _jsp_string_33 = b("\" workspace=\"");
    protected static final byte[] _jsp_string_35 = b("\">\r\n<div class=\"box-wrap\">\r\n    <div class=\"left-menu\">\r\n        <div class=\"menu-head\"><h4>系统设置</h4></div>\r\n");
    protected static final byte[] _jsp_string_36 = b("        <div id=\"\" class=\"menu-body\" style=\"margin-top: 10px; white-space: nowrap; overflow: auto;\">\r\n");
    protected static final byte[] _jsp_string_37 = b("            <ul class=\"menu\">\r\n                <li class=\"active\"><a href=\"javascript:void(0)\">文本选项</a></li>\r\n");
    protected static final byte[] _jsp_string_38 = b("            </ul>\r\n        </div>\r\n    </div>\r\n    <div style=\"margin-left: 244px; height: 100%;\">\r\n");
    protected static final byte[] _jsp_string_39 = b("        <div id=\"finder-panel\" class=\"form\">\r\n            <div class=\"menu-panel\"><h4>文本选项</h4></div>\r\n");
    protected static final byte[] _jsp_string_40 = b("            <div class=\"form-row\">\r\n                <div class=\"form-label\">主题：</div>\r\n");
    protected static final byte[] _jsp_string_41 = b("                <div class=\"form-c300\">\r\n                    <div class=\"form-field\">\r\n");
    protected static final byte[] _jsp_string_42 = b("                        <select name=\"theme\">\r\n                            <option value=\"Django\">Django</option>\r\n");
    protected static final byte[] _jsp_string_43 = b("                            <option value=\"Eclipse\">Eclipse</option>\r\n                            <option value=\"Emacs\">Emacs</option>\r\n");
    protected static final byte[] _jsp_string_44 = b("                            <option value=\"FadeToGrey\">FadeToGrey</option>\r\n                            <option value=\"MDUltra\">MDUltra</option>\r\n");
    protected static final byte[] _jsp_string_45 = b("                            <option value=\"Midnight\">Midnight</option>\r\n                            <option value=\"RDark\">RDark</option>\r\n");
    protected static final byte[] _jsp_string_46 = b("                        </select>\r\n                    </div>\r\n                </div>\r\n");
    protected static final byte[] _jsp_string_47 = b("                <div class=\"form-m300\">\r\n                    <div class=\"form-comment\">主题。</div>\r\n");
    protected static final byte[] _jsp_string_48 = b("                </div>\r\n            </div>\r\n            <div class=\"form-row\">\r\n");
    protected static final byte[] _jsp_string_49 = b("                <div class=\"form-label\">字符集：</div>\r\n                <div class=\"form-c300\">\r\n");
    protected static final byte[] _jsp_string_50 = b("                    <div class=\"form-field\"><select name=\"charset\"></select></div>\r\n");
    protected static final byte[] _jsp_string_51 = b("                </div>\r\n                <div class=\"form-m300\">\r\n                    <div class=\"form-comment\">字符集。工作空间设置的字符集优先于此处的设置。</div>\r\n");
    protected static final byte[] _jsp_string_52 = b("                </div>\r\n            </div>\r\n            <div class=\"form-row\">\r\n");
    protected static final byte[] _jsp_string_53 = b("                <div class=\"form-label\">字体：</div>\r\n                <div class=\"form-c300\">\r\n");
    protected static final byte[] _jsp_string_54 = b("                    <div class=\"form-field\">\r\n                        <select name=\"fontFamily\">\r\n");
    protected static final byte[] _jsp_string_55 = b("                            <option value=\"Andale Mono\">Andale Mono</option>\r\n                            <option value=\"Anonymous\">Anonymous</option>\r\n");
    protected static final byte[] _jsp_string_56 = b("                            <option value=\"Consolas\">Consolas</option>\r\n                            <option value=\"Courier New\">Courier New</option>\r\n");
    protected static final byte[] _jsp_string_57 = b("                            <option value=\"Dejavu\">Dejavu</option>\r\n                            <option value=\"DroidMono\">DroidMono</option>\r\n");
    protected static final byte[] _jsp_string_58 = b("                            <option value=\"EnvyR\">EnvyR</option>\r\n                            <option value=\"FiraCode\">FiraCode</option>\r\n");
    protected static final byte[] _jsp_string_59 = b("                            <option value=\"Hasklig\">Hasklig</option>\r\n                            <option value=\"InputMono\">InputMono</option>\r\n");
    protected static final byte[] _jsp_string_60 = b("                            <option value=\"liberation\">liberation</option>\r\n                            <option value=\"Lucida Console\">Lucida Console</option>\r\n");
    protected static final byte[] _jsp_string_61 = b("                            <option value=\"LucidaMono\">LucidaMono</option>\r\n                            <option value=\"Monaco\">Monaco</option>\r\n");
    protected static final byte[] _jsp_string_62 = b("                            <option value=\"Monoid\">Monoid</option>\r\n                            <option value=\"Profont\">Profont</option>\r\n");
    protected static final byte[] _jsp_string_63 = b("                            <option value=\"SourceCode\">SourceCode</option>\r\n                            <option value=\"UbuntuMono\">UbuntuMono</option>\r\n");
    protected static final byte[] _jsp_string_64 = b("                        </select>\r\n                    </div>\r\n                </div>\r\n");
    protected static final byte[] _jsp_string_65 = b("                <div class=\"form-m300\">\r\n                    <div id=\"fontExample\">我是字体示例 abcd ABCD 123</div>\r\n");
    protected static final byte[] _jsp_string_66 = b("                </div>\r\n            </div>\r\n            <div class=\"form-row\">\r\n");
    protected static final byte[] _jsp_string_67 = b("                <div class=\"form-label\">字体颜色：</div>\r\n                <div class=\"form-c300\">\r\n");
    protected static final byte[] _jsp_string_68 = b("                    <div class=\"form-field\">\r\n                        <input name=\"fontColor\" type=\"text\" class=\"color-text\" value=\"\"/>\r\n");
    protected static final byte[] _jsp_string_69 = b("                        <input name=\"fontColorPicker\" type=\"text\" class=\"color-picker\" readonly=\"true\" value=\"\"/>\r\n");
    protected static final byte[] _jsp_string_70 = b("                    </div>\r\n                </div>\r\n                <div class=\"form-m300\">\r\n");
    protected static final byte[] _jsp_string_71 = b("                    <div class=\"form-comment\">字体颜色。</div>\r\n                </div>\r\n");
    protected static final byte[] _jsp_string_72 = b("            </div>\r\n            <div class=\"form-row\">\r\n                <div class=\"form-label\">背景颜色：</div>\r\n");
    protected static final byte[] _jsp_string_73 = b("                <div class=\"form-c300\">\r\n                    <div class=\"form-field\">\r\n");
    protected static final byte[] _jsp_string_74 = b("                        <input name=\"backgroundColor\" type=\"text\" class=\"color-text\" value=\"\"/>\r\n");
    protected static final byte[] _jsp_string_75 = b("                        <input name=\"backgroundColorPicker\" type=\"text\" class=\"color-picker\" readonly=\"true\" value=\"\"/>\r\n");
    protected static final byte[] _jsp_string_76 = b("                    </div>\r\n                </div>\r\n                <div class=\"form-m300\">\r\n");
    protected static final byte[] _jsp_string_77 = b("                    <div class=\"form-comment\">背景颜色。</div>\r\n                </div>\r\n");
    protected static final byte[] _jsp_string_78 = b("            </div>\r\n            <div class=\"button\">\r\n                <button id=\"default-btn\" class=\"button\">恢复默认</button>\r\n");
    protected static final byte[] _jsp_string_79 = b("                <button id=\"ensure-btn\" class=\"button ensure\">确 定</button>\r\n                <button id=\"cancel-btn\" class=\"button cancel\">取 消 </button>\r\n");
    protected static final byte[] _jsp_string_80 = b("            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n</body>\r\n</html>\r\n");

}
