/*
 * $RCSfile: ConfigListTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 */
package com.skin.finder.admin.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import java.util.List;
import com.skin.finder.cluster.Cluster;
import com.skin.finder.cluster.Host;


/**
 * <p>Title: ConfigListTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class ConfigListTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final ConfigListTemplate instance = new ConfigListTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();


    Cluster cluster = (Cluster)(request.getAttribute("cluster"));
    List<Host> hosts = cluster.getHosts();

        out.write(_jsp_string_5, 0, _jsp_string_5.length);
        out.write(_jsp_string_6, 0, _jsp_string_6.length);
        out.write(_jsp_string_7, 0, _jsp_string_7.length);
        out.write(_jsp_string_8, 0, _jsp_string_8.length);
        out.write(_jsp_string_9, 0, _jsp_string_9.length);
        out.write(_jsp_string_10, 0, _jsp_string_10.length);
        out.write(_jsp_string_11, 0, _jsp_string_11.length);
        out.write(_jsp_string_12, 0, _jsp_string_12.length);
        out.write(_jsp_string_13, 0, _jsp_string_13.length);
        out.write(_jsp_string_14, 0, _jsp_string_14.length);
        out.write(_jsp_string_15, 0, _jsp_string_15.length);
        out.write(_jsp_string_16, 0, _jsp_string_16.length);
        out.write(_jsp_string_17, 0, _jsp_string_17.length);
        out.write(_jsp_string_18, 0, _jsp_string_18.length);
        out.write(_jsp_string_19, 0, _jsp_string_19.length);
        out.write(_jsp_string_20, 0, _jsp_string_20.length);
        out.write(_jsp_string_21, 0, _jsp_string_21.length);
        out.write(_jsp_string_22, 0, _jsp_string_22.length);
        out.write(_jsp_string_23, 0, _jsp_string_23.length);
        out.write(_jsp_string_24, 0, _jsp_string_24.length);
        out.write(_jsp_string_25, 0, _jsp_string_25.length);
        out.write(_jsp_string_26, 0, _jsp_string_26.length);
        out.write(_jsp_string_27, 0, _jsp_string_27.length);
        out.write(_jsp_string_28, 0, _jsp_string_28.length);
        out.write(_jsp_string_29, 0, _jsp_string_29.length);
        out.write(_jsp_string_30, 0, _jsp_string_30.length);
        out.write(_jsp_string_31, 0, _jsp_string_31.length);
        out.write(_jsp_string_32, 0, _jsp_string_32.length);
        out.write(_jsp_string_33, 0, _jsp_string_33.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_string_35, 0, _jsp_string_35.length);
        out.write(_jsp_string_36, 0, _jsp_string_36.length);
        out.write(_jsp_string_37, 0, _jsp_string_37.length);
        out.write(_jsp_string_38, 0, _jsp_string_38.length);
        out.write(_jsp_string_39, 0, _jsp_string_39.length);
        out.write(_jsp_string_40, 0, _jsp_string_40.length);

        for(Host host : hosts) {
    
        out.write(_jsp_string_42, 0, _jsp_string_42.length);
        this.write(out, (host.getName()));
        out.write(_jsp_string_44, 0, _jsp_string_44.length);
        this.write(out, (host.getName()));
        out.write(_jsp_string_46, 0, _jsp_string_46.length);
        this.write(out, (host.getDisplayName()));
        out.write(_jsp_string_48, 0, _jsp_string_48.length);
        this.write(out, (host.getUrl()));
        out.write(_jsp_string_50, 0, _jsp_string_50.length);
        out.write(_jsp_string_51, 0, _jsp_string_51.length);
        this.write(out, (host.getName()));
        out.write(_jsp_string_53, 0, _jsp_string_53.length);

        }
    
        out.write(_jsp_string_55, 0, _jsp_string_55.length);
        this.write(out, request.getAttribute("masterName"));
        out.write(_jsp_string_57, 0, _jsp_string_57.length);
        this.write(out, request.getAttribute("confVersion"));
        out.write(_jsp_string_59, 0, _jsp_string_59.length);

        out.flush();
    }

    protected static final byte[] _jsp_string_5 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_string_6 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_string_7 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>Finder - Powered by Finder</title>\r\n");
    protected static final byte[] _jsp_string_8 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_string_9 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/admin/css/form.css\"/>\r\n");
    protected static final byte[] _jsp_string_10 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.7.2.min.js\"></script>\r\n");
    protected static final byte[] _jsp_string_11 = b("<script type=\"text/javascript\" src=\"?action=res&path=/admin/base.js\"></script>\r\n");
    protected static final byte[] _jsp_string_12 = b("<script type=\"text/javascript\">\r\n<!--\r\njQuery(function() {\r\n    var master = PageContext.getAttribute(\"master-name\");\r\n");
    protected static final byte[] _jsp_string_13 = b("    var table = document.getElementById(\"host-table\");\r\n    var rows = table.rows;\r\n");
    protected static final byte[] _jsp_string_14 = b("\r\n    for(var i = 0; i < rows.length; i++) {\r\n        var tr = rows[i];\r\n        var hostName = tr.getAttribute(\"hostName\");\r\n");
    protected static final byte[] _jsp_string_15 = b("\r\n        if(hostName == null || hostName == undefined) {\r\n            continue;\r\n");
    protected static final byte[] _jsp_string_16 = b("        }\r\n\r\n        if(hostName == master) {\r\n            var src = jQuery(tr).find(\"td a.conf-sync\");\r\n");
    protected static final byte[] _jsp_string_17 = b("            src.attr(\"class\", \"btn disabled\");\r\n        }\r\n    }\r\n});\r\n\r\njQuery(function() {\r\n");
    protected static final byte[] _jsp_string_18 = b("    /**\r\n     * 1. 遍历所有host, 发起ajax请求获取目标主机的host.xml的版本号\r\n     */\r\n    var handler = function(index) {\r\n");
    protected static final byte[] _jsp_string_19 = b("        if(index == null || index == undefined) {\r\n            return;\r\n        }\r\n");
    protected static final byte[] _jsp_string_20 = b("\r\n        var table = document.getElementById(\"host-table\");\r\n        var rows = table.rows;\r\n");
    protected static final byte[] _jsp_string_21 = b("\r\n        if(index >= rows.length) {\r\n            return;\r\n        }\r\n\r\n        var tr = rows[index];\r\n");
    protected static final byte[] _jsp_string_22 = b("        var hostName = tr.getAttribute(\"hostName\");\r\n        var version = PageContext.getAttribute(\"master-config-version\");\r\n");
    protected static final byte[] _jsp_string_23 = b("\r\n        if(hostName == null || hostName == undefined) {\r\n            return;\r\n");
    protected static final byte[] _jsp_string_24 = b("        }\r\n\r\n        jQuery.ajax({\r\n            \"type\": \"get\",\r\n            \"url\": \"?action=agent.conf.version&host=\" + encodeURIComponent(hostName),\r\n");
    protected static final byte[] _jsp_string_25 = b("            \"dataType\": \"json\",\r\n            \"error\": function() {\r\n                jQuery(tr).find(\"td.version\").html(\"系统错误\");\r\n");
    protected static final byte[] _jsp_string_26 = b("                handler(index + 1);\r\n            },\r\n            \"success\": function(response) {\r\n");
    protected static final byte[] _jsp_string_27 = b("                if(response.status != 200) {\r\n                    jQuery(tr).find(\"td.version\").attr(\"title\", response.message);\r\n");
    protected static final byte[] _jsp_string_28 = b("                    jQuery(tr).find(\"td.version\").html(\"系统错误\");\r\n                }\r\n");
    protected static final byte[] _jsp_string_29 = b("                else {\r\n                    if(response.value != version) {\r\n                        jQuery(tr).find(\"td.version\").attr(\"title\", \"该节点配置与master节点不一致，请从master同步数据。\");\r\n");
    protected static final byte[] _jsp_string_30 = b("                        jQuery(tr).find(\"td.version\").html(\"<span class=\\\"red\\\">\" + response.value + \"</span>\");\r\n");
    protected static final byte[] _jsp_string_31 = b("                    }\r\n                    else {\r\n                        jQuery(tr).find(\"td.version\").html(\"<span>\" + response.value + \"</span>\");\r\n");
    protected static final byte[] _jsp_string_32 = b("                    }\r\n                }\r\n                handler(index + 1);\r\n            }\r\n");
    protected static final byte[] _jsp_string_33 = b("        });\r\n    };\r\n    handler(1);\r\n});\r\n//-->\r\n</script>\r\n</head>\r\n<body contextPath=\"");
    protected static final byte[] _jsp_string_35 = b("\">\r\n<div class=\"menu-bar\">\r\n    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.history.back();\"><span class=\"back\"></span>返回</a>\r\n");
    protected static final byte[] _jsp_string_36 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.location.reload();\"><span class=\"refresh\"></span>刷新</a>\r\n");
    protected static final byte[] _jsp_string_37 = b("    <span class=\"seperator\"></span>\r\n    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.location.href='?action=admin.config.edit';\"><span class=\"refresh\"></span>编辑</a>\r\n");
    protected static final byte[] _jsp_string_38 = b("</div>\r\n<table id=\"host-table\" class=\"list\">\r\n    <tr class=\"head\">\r\n        <td class=\"w200\">Name</td>\r\n");
    protected static final byte[] _jsp_string_39 = b("        <td class=\"w200\">Display Name</td>\r\n        <td class=\"w300\">URL</td>\r\n        <td class=\"w100\">Version</td>\r\n");
    protected static final byte[] _jsp_string_40 = b("        <td>操作</td>\r\n    </tr>\r\n    ");
    protected static final byte[] _jsp_string_42 = b("    <tr hostName=\"");
    protected static final byte[] _jsp_string_44 = b("\">\r\n        <td>");
    protected static final byte[] _jsp_string_46 = b("</td>\r\n        <td>");
    protected static final byte[] _jsp_string_48 = b("</td>\r\n        <td>");
    protected static final byte[] _jsp_string_50 = b("</td>\r\n        <td class=\"version\">...</td>\r\n        <td>&nbsp;\r\n            <!-- 配置文件不同步只能登录服务器手动修改 -->\r\n");
    protected static final byte[] _jsp_string_51 = b("            <!-- a class=\"btn disabled\" href=\"javascript:void(0)\" hostName=\"");
    protected static final byte[] _jsp_string_53 = b("\">从Master同步</a -->\r\n        </td>\r\n    </tr>\r\n    ");
    protected static final byte[] _jsp_string_55 = b("</table>\r\n<div id=\"pageContext\" style=\"display: none;\" master-name=\"");
    protected static final byte[] _jsp_string_57 = b("\" master-config-version=\"");
    protected static final byte[] _jsp_string_59 = b("\"></div>\r\n</body>\r\n</html>\r\n");

}
