/*
 * $RCSfile: HostEditTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 */
package com.skin.finder.admin.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.skin.finder.cluster.Host;


/**
 * <p>Title: HostEditTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class HostEditTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final HostEditTemplate instance = new HostEditTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();


    Host host = (Host)(request.getAttribute("host"));

    if(host == null) {
        host = new Host();
    }

        out.write(_jsp_string_3, 0, _jsp_string_3.length);
        out.write(_jsp_string_4, 0, _jsp_string_4.length);
        out.write(_jsp_string_5, 0, _jsp_string_5.length);
        out.write(_jsp_string_6, 0, _jsp_string_6.length);
        out.write(_jsp_string_7, 0, _jsp_string_7.length);
        out.write(_jsp_string_8, 0, _jsp_string_8.length);
        out.write(_jsp_string_9, 0, _jsp_string_9.length);
        out.write(_jsp_string_10, 0, _jsp_string_10.length);
        out.write(_jsp_string_11, 0, _jsp_string_11.length);
        out.write(_jsp_string_12, 0, _jsp_string_12.length);
        out.write(_jsp_string_13, 0, _jsp_string_13.length);
        out.write(_jsp_string_14, 0, _jsp_string_14.length);
        out.write(_jsp_string_15, 0, _jsp_string_15.length);
        out.write(_jsp_string_16, 0, _jsp_string_16.length);
        out.write(_jsp_string_17, 0, _jsp_string_17.length);
        out.write(_jsp_string_18, 0, _jsp_string_18.length);
        out.write(_jsp_string_19, 0, _jsp_string_19.length);
        out.write(_jsp_string_20, 0, _jsp_string_20.length);
        out.write(_jsp_string_21, 0, _jsp_string_21.length);
        out.write(_jsp_string_22, 0, _jsp_string_22.length);
        out.write(_jsp_string_23, 0, _jsp_string_23.length);
        out.write(_jsp_string_24, 0, _jsp_string_24.length);
        out.write(_jsp_string_25, 0, _jsp_string_25.length);
        out.write(_jsp_string_26, 0, _jsp_string_26.length);
        out.write(_jsp_string_27, 0, _jsp_string_27.length);
        out.write(_jsp_string_28, 0, _jsp_string_28.length);
        out.write(_jsp_string_29, 0, _jsp_string_29.length);
        out.write(_jsp_string_30, 0, _jsp_string_30.length);
        out.write(_jsp_string_31, 0, _jsp_string_31.length);
        out.write(_jsp_string_32, 0, _jsp_string_32.length);
        out.write(_jsp_string_33, 0, _jsp_string_33.length);
        out.write(_jsp_string_34, 0, _jsp_string_34.length);
        out.write(_jsp_string_35, 0, _jsp_string_35.length);
        out.write(_jsp_string_36, 0, _jsp_string_36.length);
        out.write(_jsp_string_37, 0, _jsp_string_37.length);
        out.write(_jsp_string_38, 0, _jsp_string_38.length);
        out.write(_jsp_string_39, 0, _jsp_string_39.length);
        this.write(out, request.getAttribute("oldName"));
        out.write(_jsp_string_41, 0, _jsp_string_41.length);
        this.write(out, (host.getName()));
        out.write(_jsp_string_43, 0, _jsp_string_43.length);
        out.write(_jsp_string_44, 0, _jsp_string_44.length);
        out.write(_jsp_string_45, 0, _jsp_string_45.length);
        this.write(out, (host.getDisplayName()));
        out.write(_jsp_string_47, 0, _jsp_string_47.length);
        out.write(_jsp_string_48, 0, _jsp_string_48.length);
        out.write(_jsp_string_49, 0, _jsp_string_49.length);
        out.write(_jsp_string_50, 0, _jsp_string_50.length);
        this.write(out, (host.getUrl()));
        out.write(_jsp_string_52, 0, _jsp_string_52.length);
        out.write(_jsp_string_53, 0, _jsp_string_53.length);
        out.write(_jsp_string_54, 0, _jsp_string_54.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_string_56, 0, _jsp_string_56.length);

        out.flush();
    }

    protected static final byte[] _jsp_string_3 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_string_4 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_string_5 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>Finder - Powered by Finder</title>\r\n");
    protected static final byte[] _jsp_string_6 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_string_7 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/admin/css/form.css\"/>\r\n");
    protected static final byte[] _jsp_string_8 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.7.2.min.js\"></script>\r\n");
    protected static final byte[] _jsp_string_9 = b("<script type=\"text/javascript\" src=\"?action=res&path=/admin/base.js\"></script>\r\n");
    protected static final byte[] _jsp_string_10 = b("<script type=\"text/javascript\">\r\n<!--\r\njQuery(function() {\r\n    jQuery(\"#url-test\").click(function() {\r\n");
    protected static final byte[] _jsp_string_11 = b("        var requestURI = window.location.pathname;\r\n        var hostUrl = jQuery.trim(jQuery(\"input[name=hostUrl]\").val());\r\n");
    protected static final byte[] _jsp_string_12 = b("\r\n        if(hostUrl.length < 1) {\r\n            alert(\"请输入Host URL!\");\r\n            return;\r\n");
    protected static final byte[] _jsp_string_13 = b("        }\r\n\r\n        jQuery.ajax({\r\n            type: \"post\",\r\n            url: requestURI + \"?action=admin.host.test\",\r\n");
    protected static final byte[] _jsp_string_14 = b("            dataType: \"json\",\r\n            data: \"hostUrl=\" + encodeURIComponent(hostUrl),\r\n");
    protected static final byte[] _jsp_string_15 = b("            error: function(req, status, error) {\r\n                alert(\"系统错误，请稍后再试！\");\r\n");
    protected static final byte[] _jsp_string_16 = b("            },\r\n            success: function(result) {\r\n                if(result.status != 200) {\r\n");
    protected static final byte[] _jsp_string_17 = b("                    alert(result.message);\r\n                    return;\r\n                }\r\n");
    protected static final byte[] _jsp_string_18 = b("                alert(\"测试成功！\");\r\n            }\r\n        });\r\n    });\r\n\r\n    jQuery(\"#submit\").click(function() {\r\n");
    protected static final byte[] _jsp_string_19 = b("        var oldName = jQuery.trim(jQuery(\"input[name=oldName]\").val());\r\n        var hostName = jQuery.trim(jQuery(\"input[name=hostName]\").val());\r\n");
    protected static final byte[] _jsp_string_20 = b("        var displayName = jQuery.trim(jQuery(\"input[name=displayName]\").val());\r\n");
    protected static final byte[] _jsp_string_21 = b("        var hostUrl = jQuery.trim(jQuery(\"input[name=hostUrl]\").val());\r\n\r\n        if(hostName.length < 1) {\r\n");
    protected static final byte[] _jsp_string_22 = b("            alert(\"主机名不能为空！\");\r\n            return;\r\n        }\r\n\r\n        if(hostUrl.length < 1) {\r\n");
    protected static final byte[] _jsp_string_23 = b("            alert(\"主机URL不能为空！\");\r\n            return;\r\n        }\r\n\r\n        var params = [];\r\n");
    protected static final byte[] _jsp_string_24 = b("        var requestURI = window.location.pathname;\r\n        params[params.length] = \"oldName=\" + encodeURIComponent(oldName);\r\n");
    protected static final byte[] _jsp_string_25 = b("        params[params.length] = \"hostName=\" + encodeURIComponent(hostName);\r\n        params[params.length] = \"displayName=\" + encodeURIComponent(displayName);\r\n");
    protected static final byte[] _jsp_string_26 = b("        params[params.length] = \"hostUrl=\" + encodeURIComponent(hostUrl);\r\n\r\n        jQuery.ajax({\r\n");
    protected static final byte[] _jsp_string_27 = b("            type: \"post\",\r\n            url: requestURI + \"?action=admin.host.save\",\r\n");
    protected static final byte[] _jsp_string_28 = b("            dataType: \"json\",\r\n            data: params.join(\"&\"),\r\n            error: function(req, status, error) {\r\n");
    protected static final byte[] _jsp_string_29 = b("                alert(\"系统错误，请稍后再试！\");\r\n            },\r\n            success: function(result) {\r\n");
    protected static final byte[] _jsp_string_30 = b("                if(result.status != 200) {\r\n                    alert(result.message);\r\n");
    protected static final byte[] _jsp_string_31 = b("                    return;\r\n                }\r\n                alert(\"操作成功！\");\r\n");
    protected static final byte[] _jsp_string_32 = b("                window.location.href = \"?action=admin.host.list\";\r\n            }\r\n");
    protected static final byte[] _jsp_string_33 = b("        });\r\n    });\r\n});\r\n//-->\r\n</script>\r\n</head>\r\n<body>\r\n<div class=\"menu-bar\">\r\n");
    protected static final byte[] _jsp_string_34 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.history.back();\"><span class=\"back\"></span>返回</a>\r\n");
    protected static final byte[] _jsp_string_35 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.location.reload();\"><span class=\"refresh\"></span>刷新</a>\r\n");
    protected static final byte[] _jsp_string_36 = b("    <span class=\"seperator\"></span>\r\n</div>\r\n<div class=\"form\">\r\n    <div class=\"title\"><h4>主机编辑</h4></div>\r\n");
    protected static final byte[] _jsp_string_37 = b("    <ul class=\"tips\">\r\n        <li>\r\n            <div style=\"color: #ff0000;\">如果修改了master，在添加完所有主机之后请到系统设置-一般设置，重新保存并同步到集群;</div>\r\n");
    protected static final byte[] _jsp_string_38 = b("        </li>\r\n    </ul>\r\n    <div class=\"form-row\">\r\n        <div class=\"form-label\">Host Name：</div>\r\n");
    protected static final byte[] _jsp_string_39 = b("        <div class=\"form-c300\">\r\n            <div class=\"form-field\">\r\n                <input name=\"oldName\" type=\"hidden\" value=\"");
    protected static final byte[] _jsp_string_41 = b("\"/>\r\n                <input name=\"hostName\" type=\"text\" class=\"text w200\" placeholder=\"Host Name\" value=\"");
    protected static final byte[] _jsp_string_43 = b("\"/>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n            <div class=\"form-comment\">主机名。字母和数字开头，允许包含的字符: [a-z], [A-Z], [0-9], [-_.:@].</div>\r\n");
    protected static final byte[] _jsp_string_44 = b("        </div>\r\n    </div>\r\n    <div class=\"form-row\">\r\n        <div class=\"form-label\">Display Name：</div>\r\n");
    protected static final byte[] _jsp_string_45 = b("        <div class=\"form-c300\">\r\n            <div class=\"form-field\">\r\n                <input name=\"displayName\" type=\"text\" class=\"text w200\" placeholder=\"Display Name\" value=\"");
    protected static final byte[] _jsp_string_47 = b("\"/>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n            <div class=\"form-comment\">显示名。</div>\r\n");
    protected static final byte[] _jsp_string_48 = b("        </div>\r\n    </div>\r\n    <div class=\"form-row\">\r\n        <div class=\"form-label\">Host URL:</div>\r\n");
    protected static final byte[] _jsp_string_49 = b("        <div class=\"form-comment\">Finder的访问地址。一般为http://IP:PORT/finder，如果使用了contextPath，finder的访问地址为：http://IP:PORT/[CONTEXT_PATH]/finder</div>\r\n");
    protected static final byte[] _jsp_string_50 = b("        <div class=\"form-field\">\r\n            <input name=\"hostUrl\" type=\"text\" class=\"text w400\" placeholder=\"Host URL\" value=\"");
    protected static final byte[] _jsp_string_52 = b("\"/>\r\n            <button id=\"url-test\" class=\"button ensure\">测 试</button>\r\n        </div>\r\n");
    protected static final byte[] _jsp_string_53 = b("    </div>\r\n\r\n    <div class=\"button\">\r\n        <button id=\"submit\" class=\"button ensure\">保 存</button>\r\n");
    protected static final byte[] _jsp_string_54 = b("    </div>\r\n</div>\r\n<div id=\"pageContext\" style=\"display: none;\" contextPath=\"");
    protected static final byte[] _jsp_string_56 = b("\"></div>\r\n</body>\r\n</html>");

}
