/*
 * $RCSfile: MenuXmlTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 */
package com.skin.finder.admin.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;



/**
 * <p>Title: MenuXmlTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class MenuXmlTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final MenuXmlTemplate instance = new MenuXmlTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/xml; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_string_1, 0, _jsp_string_1.length);
        out.write(_jsp_string_2, 0, _jsp_string_2.length);

        if(Boolean.TRUE.equals(request.getAttribute("userSupport"))) {
    
        out.write(_jsp_string_4, 0, _jsp_string_4.length);
        out.write(_jsp_string_5, 0, _jsp_string_5.length);
        out.write(_jsp_string_6, 0, _jsp_string_6.length);
        out.write(_jsp_string_7, 0, _jsp_string_7.length);

        }
    
        out.write(_jsp_string_9, 0, _jsp_string_9.length);
        out.write(_jsp_string_10, 0, _jsp_string_10.length);
        out.write(_jsp_string_11, 0, _jsp_string_11.length);
        out.write(_jsp_string_12, 0, _jsp_string_12.length);
        out.write(_jsp_string_13, 0, _jsp_string_13.length);
        out.write(_jsp_string_14, 0, _jsp_string_14.length);

        out.flush();
    }

    protected static final byte[] _jsp_string_1 = b("<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<tree>\r\n<!-- Finder - Powered by Finder -->\r\n");
    protected static final byte[] _jsp_string_2 = b("    <treeNode title=\"主机管理\" href=\"?action=admin.host.list\"/>\r\n    ");
    protected static final byte[] _jsp_string_4 = b("    <treeNode title=\"用户管理\" href=\"?action=admin.user.query\" expand=\"true\">\r\n        <treeNode title=\"全部用户\" href=\"?action=admin.user.list\"/>\r\n");
    protected static final byte[] _jsp_string_5 = b("        <treeNode title=\"添加用户\" href=\"?action=admin.user.edit\"/>\r\n        <treeNode title=\"修改用户\" href=\"?action=admin.user.query\"/>\r\n");
    protected static final byte[] _jsp_string_6 = b("        <treeNode title=\"删除用户\" href=\"?action=admin.user.query\"/>\r\n    </treeNode>\r\n");
    protected static final byte[] _jsp_string_7 = b("    ");
    protected static final byte[] _jsp_string_9 = b("    <treeNode title=\"权限管理\" href=\"?action=admin.user.host.policy\" expand=\"true\">\r\n");
    protected static final byte[] _jsp_string_10 = b("        <treeNode title=\"主机权限\" href=\"?action=admin.user.host.policy\"/>\r\n        <treeNode title=\"文件权限\" href=\"?action=admin.user.file.policy\"/>\r\n");
    protected static final byte[] _jsp_string_11 = b("    </treeNode>\r\n    <treeNode title=\"系统设置\" href=\"?action=admin.config.list\" expand=\"true\">\r\n");
    protected static final byte[] _jsp_string_12 = b("        <treeNode title=\"一般设置\" href=\"?action=admin.config.edit\"/>\r\n        <treeNode title=\"安全设置\" href=\"?action=admin.security.config.edit\"/>\r\n");
    protected static final byte[] _jsp_string_13 = b("    </treeNode>\r\n    <treeNode title=\"系统更新\" href=\"?action=admin.upgrade.index\"/>\r\n");
    protected static final byte[] _jsp_string_14 = b("    <treeNode title=\"系统信息\" href=\"?action=admin.system.info\"/>\r\n</tree>\r\n");

}
