/*
 * $RCSfile: SecurityConfigEditTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 */
package com.skin.finder.admin.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.skin.finder.config.ConfigFactory;


/**
 * <p>Title: SecurityConfigEditTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class SecurityConfigEditTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final SecurityConfigEditTemplate instance = new SecurityConfigEditTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_string_2, 0, _jsp_string_2.length);
        out.write(_jsp_string_3, 0, _jsp_string_3.length);
        out.write(_jsp_string_4, 0, _jsp_string_4.length);
        out.write(_jsp_string_5, 0, _jsp_string_5.length);
        out.write(_jsp_string_6, 0, _jsp_string_6.length);
        out.write(_jsp_string_7, 0, _jsp_string_7.length);
        out.write(_jsp_string_8, 0, _jsp_string_8.length);
        out.write(_jsp_string_9, 0, _jsp_string_9.length);
        out.write(_jsp_string_10, 0, _jsp_string_10.length);
        out.write(_jsp_string_11, 0, _jsp_string_11.length);
        out.write(_jsp_string_12, 0, _jsp_string_12.length);
        out.write(_jsp_string_13, 0, _jsp_string_13.length);
        out.write(_jsp_string_14, 0, _jsp_string_14.length);
        out.write(_jsp_string_15, 0, _jsp_string_15.length);
        out.write(_jsp_string_16, 0, _jsp_string_16.length);
        out.write(_jsp_string_17, 0, _jsp_string_17.length);
        out.write(_jsp_string_18, 0, _jsp_string_18.length);
        out.write(_jsp_string_19, 0, _jsp_string_19.length);
        out.write(_jsp_string_20, 0, _jsp_string_20.length);
        out.write(_jsp_string_21, 0, _jsp_string_21.length);
        out.write(_jsp_string_22, 0, _jsp_string_22.length);
        out.write(_jsp_string_23, 0, _jsp_string_23.length);
        out.write(_jsp_string_24, 0, _jsp_string_24.length);
        out.write(_jsp_string_25, 0, _jsp_string_25.length);
        out.write(_jsp_string_26, 0, _jsp_string_26.length);
        out.write(_jsp_string_27, 0, _jsp_string_27.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_string_29, 0, _jsp_string_29.length);
        out.write(_jsp_string_30, 0, _jsp_string_30.length);
        out.write(_jsp_string_31, 0, _jsp_string_31.length);
        out.write(_jsp_string_32, 0, _jsp_string_32.length);
        out.write(_jsp_string_33, 0, _jsp_string_33.length);
        this.write(out, (ConfigFactory.getAdmin()));
        out.write(_jsp_string_35, 0, _jsp_string_35.length);
        out.write(_jsp_string_36, 0, _jsp_string_36.length);
        out.write(_jsp_string_37, 0, _jsp_string_37.length);
        this.write(out, (ConfigFactory.getSecurityKey()));
        out.write(_jsp_string_39, 0, _jsp_string_39.length);
        out.write(_jsp_string_40, 0, _jsp_string_40.length);
        out.write(_jsp_string_41, 0, _jsp_string_41.length);
        out.write(_jsp_string_42, 0, _jsp_string_42.length);
        this.write(out, (ConfigFactory.getSessionName()));
        out.write(_jsp_string_44, 0, _jsp_string_44.length);
        out.write(_jsp_string_45, 0, _jsp_string_45.length);
        out.write(_jsp_string_46, 0, _jsp_string_46.length);
        this.write(out, (ConfigFactory.getSessionKey()));
        out.write(_jsp_string_48, 0, _jsp_string_48.length);
        out.write(_jsp_string_49, 0, _jsp_string_49.length);
        out.write(_jsp_string_50, 0, _jsp_string_50.length);
        out.write(_jsp_string_51, 0, _jsp_string_51.length);
        out.write(_jsp_string_52, 0, _jsp_string_52.length);

        out.flush();
    }

    protected static final byte[] _jsp_string_2 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_string_3 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_string_4 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>Finder - Powered by Finder</title>\r\n");
    protected static final byte[] _jsp_string_5 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_string_6 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/admin/css/form.css\"/>\r\n");
    protected static final byte[] _jsp_string_7 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.7.2.min.js\"></script>\r\n");
    protected static final byte[] _jsp_string_8 = b("<script type=\"text/javascript\" src=\"?action=res&path=/admin/base.js\"></script>\r\n");
    protected static final byte[] _jsp_string_9 = b("<script type=\"text/javascript\">\r\n<!--\r\njQuery(function() {\r\n    jQuery(\"button.key-generate\").click(function() {\r\n");
    protected static final byte[] _jsp_string_10 = b("        var name = jQuery(this).attr(\"for\");\r\n\r\n        if(name == null) {\r\n            return;\r\n");
    protected static final byte[] _jsp_string_11 = b("        }\r\n\r\n        jQuery.ajax({\r\n            \"type\": \"get\",\r\n            \"url\": \"?action=admin.random.uuid\",\r\n");
    protected static final byte[] _jsp_string_12 = b("            \"dataType\": \"json\",\r\n            \"error\": function() {\r\n                alert(\"系统错误，请稍后再试！\");\r\n");
    protected static final byte[] _jsp_string_13 = b("            },\r\n            \"success\": function(response) {\r\n                if(response.status != 200) {\r\n");
    protected static final byte[] _jsp_string_14 = b("                    alert(response.message);\r\n                    return;\r\n                }\r\n");
    protected static final byte[] _jsp_string_15 = b("                jQuery(\"input[name=\" + name + \"]\").val(response.value);\r\n            }\r\n");
    protected static final byte[] _jsp_string_16 = b("        });\r\n    });\r\n\r\n    jQuery(\"#submit\").click(function() {\r\n        var params = {};\r\n");
    protected static final byte[] _jsp_string_17 = b("        params.adminName = jQuery.trim(jQuery(\"input[name=adminName]\").val());\r\n");
    protected static final byte[] _jsp_string_18 = b("        params.securityKey = jQuery.trim(jQuery(\"input[name=securityKey]\").val());\r\n");
    protected static final byte[] _jsp_string_19 = b("        params.sessionName = jQuery.trim(jQuery(\"input[name=sessionName]\").val());\r\n");
    protected static final byte[] _jsp_string_20 = b("        params.sessionKey = jQuery.trim(jQuery(\"input[name=sessionKey]\").val());\r\n");
    protected static final byte[] _jsp_string_21 = b("\r\n        jQuery.ajax({\r\n            \"type\": \"get\",\r\n            \"url\": \"?action=admin.security.config.save\",\r\n");
    protected static final byte[] _jsp_string_22 = b("            \"dataType\": \"json\",\r\n            \"data\": jQuery.param(params, true),\r\n");
    protected static final byte[] _jsp_string_23 = b("            \"error\": function() {\r\n                alert(\"系统错误，请稍后再试！\");\r\n            },\r\n");
    protected static final byte[] _jsp_string_24 = b("            \"success\": function(response) {\r\n                if(response.status != 200) {\r\n");
    protected static final byte[] _jsp_string_25 = b("                    alert(response.message);\r\n                }\r\n                else {\r\n");
    protected static final byte[] _jsp_string_26 = b("                    alert(\"保存并同步成功！\");\r\n                }\r\n                window.location.reload();\r\n");
    protected static final byte[] _jsp_string_27 = b("            }\r\n        });\r\n    });\r\n});\r\n//-->\r\n</script>\r\n</head>\r\n<body contextPath=\"");
    protected static final byte[] _jsp_string_29 = b("\">\r\n<div class=\"menu-bar\">\r\n    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.history.back();\"><span class=\"back\"></span>返回</a>\r\n");
    protected static final byte[] _jsp_string_30 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.location.reload();\"><span class=\"refresh\"></span>刷新</a>\r\n");
    protected static final byte[] _jsp_string_31 = b("    <span class=\"seperator\"></span>\r\n</div>\r\n<div class=\"form\">\r\n    <div class=\"title\"><h4>系统设置 - 安全设置</h4></div>\r\n");
    protected static final byte[] _jsp_string_32 = b("    <div class=\"form-row\">\r\n        <div class=\"form-label\">超级管理员：</div>\r\n        <div class=\"form-c400\">\r\n");
    protected static final byte[] _jsp_string_33 = b("            <div class=\"form-field\">\r\n                <input name=\"adminName\" type=\"text\" class=\"text w300\" placeholder=\"User Name\" value=\"");
    protected static final byte[] _jsp_string_35 = b("\"/>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n            <div class=\"form-comment\">超级管理员账号。</div>\r\n");
    protected static final byte[] _jsp_string_36 = b("        </div>\r\n    </div>\r\n    <div class=\"form-row\">\r\n        <div class=\"form-label\">安全Key：</div>\r\n");
    protected static final byte[] _jsp_string_37 = b("        <div class=\"form-c400\">\r\n            <div class=\"form-field\">\r\n                <input name=\"securityKey\" type=\"text\" class=\"text w300\" placeholder=\"Security Key\" value=\"");
    protected static final byte[] _jsp_string_39 = b("\"/>\r\n                <button id=\"url-test\" class=\"button key-generate\" for=\"securityKey\">生成</button>\r\n");
    protected static final byte[] _jsp_string_40 = b("            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n            <div class=\"form-comment\">Finder内部通讯使用的安全KEY。集群环境下，所有机器的安全KEY必须一致。强烈建议重新生成。</div>\r\n");
    protected static final byte[] _jsp_string_41 = b("        </div>\r\n    </div>\r\n    <div class=\"form-row\">\r\n        <div class=\"form-label\">会话名：</div>\r\n");
    protected static final byte[] _jsp_string_42 = b("        <div class=\"form-c400\">\r\n            <div class=\"form-field\">\r\n                <input name=\"sessionName\" type=\"text\" class=\"text w300\" placeholder=\"Session Name\" value=\"");
    protected static final byte[] _jsp_string_44 = b("\"/>\r\n            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n            <div class=\"form-comment\">会话存储的cookie名。</div>\r\n");
    protected static final byte[] _jsp_string_45 = b("        </div>\r\n    </div>\r\n    <div class=\"form-row\">\r\n        <div class=\"form-label\">会话签名Key：</div>\r\n");
    protected static final byte[] _jsp_string_46 = b("        <div class=\"form-c400\">\r\n            <div class=\"form-field\">\r\n                <input name=\"sessionKey\" type=\"text\" class=\"text w300\" placeholder=\"Session Key\" value=\"");
    protected static final byte[] _jsp_string_48 = b("\"/>\r\n                <button id=\"url-test\" class=\"button key-generate\" for=\"sessionKey\">生成</button>\r\n");
    protected static final byte[] _jsp_string_49 = b("            </div>\r\n        </div>\r\n        <div class=\"form-m300\">\r\n            <div class=\"form-comment\">会话签名使用的key。强烈建议重新生成。</div>\r\n");
    protected static final byte[] _jsp_string_50 = b("        </div>\r\n    </div>\r\n    <div class=\"button\">\r\n        <button id=\"submit\" class=\"button ensure\">保存并同步到集群</button>\r\n");
    protected static final byte[] _jsp_string_51 = b("    </div>\r\n</div>\r\n<div id=\"pageContext\" style=\"display: none;\"></div>\r\n</body>\r\n");
    protected static final byte[] _jsp_string_52 = b("</html>\r\n");

}
