/*
 * $RCSfile: SystemInfoTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 */
package com.skin.finder.admin.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.skin.finder.util.SystemInfo;
import com.skin.finder.util.Version;
import com.skin.finder.util.ServletInfo;


/**
 * <p>Title: SystemInfoTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class SystemInfoTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final SystemInfoTemplate instance = new SystemInfoTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();


    Version version = (Version)(request.getAttribute("version"));
    SystemInfo systemInfo = (SystemInfo)(request.getAttribute("systemInfo"));
    ServletInfo servletInfo = (ServletInfo)(request.getAttribute("servletInfo"));

        out.write(_jsp_string_5, 0, _jsp_string_5.length);
        out.write(_jsp_string_6, 0, _jsp_string_6.length);
        out.write(_jsp_string_7, 0, _jsp_string_7.length);
        out.write(_jsp_string_8, 0, _jsp_string_8.length);
        out.write(_jsp_string_9, 0, _jsp_string_9.length);
        out.write(_jsp_string_10, 0, _jsp_string_10.length);
        out.write(_jsp_string_11, 0, _jsp_string_11.length);
        out.write(_jsp_string_12, 0, _jsp_string_12.length);
        this.write(out, request.getAttribute("reqeustHeaders"));
        out.write(_jsp_string_14, 0, _jsp_string_14.length);
        out.write(_jsp_string_15, 0, _jsp_string_15.length);
        out.write(_jsp_string_16, 0, _jsp_string_16.length);
        out.write(_jsp_string_17, 0, _jsp_string_17.length);
        out.write(_jsp_string_18, 0, _jsp_string_18.length);
        this.write(out, request.getAttribute("hostName"));
        out.write(_jsp_string_20, 0, _jsp_string_20.length);
        this.write(out, (version.getVersionName()));
        out.write(_jsp_string_22, 0, _jsp_string_22.length);
        this.write(out, (version.getDeveloper()));
        out.write(_jsp_string_24, 0, _jsp_string_24.length);
        this.write(out, (version.getDeveloper()));
        out.write(_jsp_string_26, 0, _jsp_string_26.length);
        this.write(out, (servletInfo.getServerInfo()));
        out.write(_jsp_string_28, 0, _jsp_string_28.length);
        this.write(out, (servletInfo.getServletVersion()));
        out.write(_jsp_string_30, 0, _jsp_string_30.length);
        this.write(out, (systemInfo.getOsName()));
        out.write(_jsp_string_32, 0, _jsp_string_32.length);
        this.write(out, (systemInfo.getOsVersion()));
        out.write(_jsp_string_34, 0, _jsp_string_34.length);
        this.write(out, (systemInfo.getCpu()));
        out.write(_jsp_string_36, 0, _jsp_string_36.length);
        this.write(out, (systemInfo.getVmName()));
        out.write(_jsp_string_38, 0, _jsp_string_38.length);
        this.write(out, (systemInfo.getVmVendor()));
        out.write(_jsp_string_40, 0, _jsp_string_40.length);
        this.write(out, (systemInfo.getVmVersion()));
        out.write(_jsp_string_42, 0, _jsp_string_42.length);
        this.write(out, (systemInfo.getRuntimeName()));
        out.write(_jsp_string_44, 0, _jsp_string_44.length);
        this.write(out, (systemInfo.getRuntimeVersion()));
        out.write(_jsp_string_46, 0, _jsp_string_46.length);
        this.write(out, (systemInfo.getMaxMemory()));
        out.write(_jsp_string_48, 0, _jsp_string_48.length);
        this.write(out, (systemInfo.getMaxMemory() / 1048576));
        out.write(_jsp_string_50, 0, _jsp_string_50.length);
        this.write(out, (systemInfo.getTotalMemory()));
        out.write(_jsp_string_52, 0, _jsp_string_52.length);
        this.write(out, (systemInfo.getTotalMemory() / 1048576));
        out.write(_jsp_string_54, 0, _jsp_string_54.length);
        this.write(out, (systemInfo.getFreeMemory()));
        out.write(_jsp_string_56, 0, _jsp_string_56.length);
        this.write(out, (systemInfo.getFreeMemory() / 1048576));
        out.write(_jsp_string_58, 0, _jsp_string_58.length);

        out.flush();
    }

    protected static final byte[] _jsp_string_5 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_string_6 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_string_7 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>Finder - Powered by Finder</title>\r\n");
    protected static final byte[] _jsp_string_8 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_string_9 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/admin/css/form.css\"/>\r\n");
    protected static final byte[] _jsp_string_10 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.7.2.min.js\"></script>\r\n");
    protected static final byte[] _jsp_string_11 = b("<script type=\"text/javascript\" src=\"?action=res&path=/admin/base.js\"></script>\r\n");
    protected static final byte[] _jsp_string_12 = b("</head>\r\n<body>\r\n<!--\r\n");
    protected static final byte[] _jsp_string_14 = b("\r\n-->\r\n<div class=\"menu-bar\">\r\n    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.history.back();\"><span class=\"back\"></span>返回</a>\r\n");
    protected static final byte[] _jsp_string_15 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.location.reload();\"><span class=\"refresh\"></span>刷新</a>\r\n");
    protected static final byte[] _jsp_string_16 = b("    <span class=\"seperator\"></span>\r\n</div>\r\n<table class=\"list\">\r\n    <!-- Server Info -->\r\n");
    protected static final byte[] _jsp_string_17 = b("    <tr class=\"head\">\r\n        <td colspan=\"2\">System Info</td>\r\n    </tr>\r\n    <tr>\r\n");
    protected static final byte[] _jsp_string_18 = b("        <td class=\"w200\">Host</td>\r\n        <td>");
    protected static final byte[] _jsp_string_20 = b("</td>\r\n    </tr>\r\n    <tr>\r\n        <td class=\"w200\">Version</td>\r\n        <td>");
    protected static final byte[] _jsp_string_22 = b("</td>\r\n    </tr>\r\n    <tr>\r\n        <td class=\"w200\">Developer</td>\r\n        <td><a href=\"");
    protected static final byte[] _jsp_string_24 = b("\" target=\"_blank\">");
    protected static final byte[] _jsp_string_26 = b("</a></td>\r\n    </tr>\r\n    <tr>\r\n        <td class=\"w200\">Server</td>\r\n        <td>");
    protected static final byte[] _jsp_string_28 = b("</td>\r\n    </tr>\r\n    <tr>\r\n        <td>ServletVersion</td>\r\n        <td>");
    protected static final byte[] _jsp_string_30 = b("</td>\r\n    </tr>\r\n    <!-- System Info -->\r\n    <tr>\r\n        <td>OS</td>\r\n        <td>");
    protected static final byte[] _jsp_string_32 = b(" (");
    protected static final byte[] _jsp_string_34 = b(") (");
    protected static final byte[] _jsp_string_36 = b(")</td>\r\n    </tr>\r\n    <tr>\r\n        <td>Virtual Machine Name</td>\r\n        <td>");
    protected static final byte[] _jsp_string_38 = b("</td>\r\n    </tr>\r\n    <tr>\r\n        <td>Virtual Machine Vendor</td>\r\n        <td>");
    protected static final byte[] _jsp_string_40 = b("</td>\r\n    </tr>\r\n    <tr>\r\n        <td>Virtual Machine Version</td>\r\n        <td>");
    protected static final byte[] _jsp_string_42 = b("</td>\r\n    </tr>\r\n    <tr>\r\n        <td>Runtime Name</td>\r\n        <td>");
    protected static final byte[] _jsp_string_44 = b("</td>\r\n    </tr>\r\n    <tr>\r\n        <td>Runtime Version</td>\r\n        <td>");
    protected static final byte[] _jsp_string_46 = b("</td>\r\n    </tr>\r\n    <tr>\r\n        <td>Max Memory</td>\r\n        <td>");
    protected static final byte[] _jsp_string_48 = b(" (");
    protected static final byte[] _jsp_string_50 = b("M)</td>\r\n    </tr>\r\n    <tr>\r\n        <td>Total Memory</td>\r\n        <td>");
    protected static final byte[] _jsp_string_52 = b(" (");
    protected static final byte[] _jsp_string_54 = b("M)</td>\r\n    </tr>\r\n    <tr>\r\n        <td>Free Memory</td>\r\n        <td>");
    protected static final byte[] _jsp_string_56 = b(" (");
    protected static final byte[] _jsp_string_58 = b("M)</td>\r\n    </tr>\r\n</table>\r\n<div style=\"height: 200px;\"></div>\r\n</body>\r\n</html>");

}
