/*
 * $RCSfile: UserHostPolicyTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 */
package com.skin.finder.admin.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;



/**
 * <p>Title: UserHostPolicyTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class UserHostPolicyTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final UserHostPolicyTemplate instance = new UserHostPolicyTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_string_1, 0, _jsp_string_1.length);
        out.write(_jsp_string_2, 0, _jsp_string_2.length);
        out.write(_jsp_string_3, 0, _jsp_string_3.length);
        out.write(_jsp_string_4, 0, _jsp_string_4.length);
        out.write(_jsp_string_5, 0, _jsp_string_5.length);
        out.write(_jsp_string_6, 0, _jsp_string_6.length);
        out.write(_jsp_string_7, 0, _jsp_string_7.length);
        out.write(_jsp_string_8, 0, _jsp_string_8.length);
        out.write(_jsp_string_9, 0, _jsp_string_9.length);
        out.write(_jsp_string_10, 0, _jsp_string_10.length);
        out.write(_jsp_string_11, 0, _jsp_string_11.length);
        out.write(_jsp_string_12, 0, _jsp_string_12.length);
        out.write(_jsp_string_13, 0, _jsp_string_13.length);
        out.write(_jsp_string_14, 0, _jsp_string_14.length);
        out.write(_jsp_string_15, 0, _jsp_string_15.length);
        out.write(_jsp_string_16, 0, _jsp_string_16.length);
        out.write(_jsp_string_17, 0, _jsp_string_17.length);
        out.write(_jsp_string_18, 0, _jsp_string_18.length);
        out.write(_jsp_string_19, 0, _jsp_string_19.length);
        out.write(_jsp_string_20, 0, _jsp_string_20.length);
        out.write(_jsp_string_21, 0, _jsp_string_21.length);
        out.write(_jsp_string_22, 0, _jsp_string_22.length);
        out.write(_jsp_string_23, 0, _jsp_string_23.length);
        out.write(_jsp_string_24, 0, _jsp_string_24.length);
        out.write(_jsp_string_25, 0, _jsp_string_25.length);
        out.write(_jsp_string_26, 0, _jsp_string_26.length);
        out.write(_jsp_string_27, 0, _jsp_string_27.length);
        out.write(_jsp_string_28, 0, _jsp_string_28.length);
        out.write(_jsp_string_29, 0, _jsp_string_29.length);
        out.write(_jsp_string_30, 0, _jsp_string_30.length);
        out.write(_jsp_string_31, 0, _jsp_string_31.length);
        out.write(_jsp_string_32, 0, _jsp_string_32.length);
        out.write(_jsp_string_33, 0, _jsp_string_33.length);
        out.write(_jsp_string_34, 0, _jsp_string_34.length);
        out.write(_jsp_string_35, 0, _jsp_string_35.length);
        out.write(_jsp_string_36, 0, _jsp_string_36.length);
        out.write(_jsp_string_37, 0, _jsp_string_37.length);
        out.write(_jsp_string_38, 0, _jsp_string_38.length);
        out.write(_jsp_string_39, 0, _jsp_string_39.length);
        out.write(_jsp_string_40, 0, _jsp_string_40.length);
        out.write(_jsp_string_41, 0, _jsp_string_41.length);
        out.write(_jsp_string_42, 0, _jsp_string_42.length);
        out.write(_jsp_string_43, 0, _jsp_string_43.length);
        out.write(_jsp_string_44, 0, _jsp_string_44.length);
        out.write(_jsp_string_45, 0, _jsp_string_45.length);
        out.write(_jsp_string_46, 0, _jsp_string_46.length);
        out.write(_jsp_string_47, 0, _jsp_string_47.length);
        out.write(_jsp_string_48, 0, _jsp_string_48.length);
        out.write(_jsp_string_49, 0, _jsp_string_49.length);
        out.write(_jsp_string_50, 0, _jsp_string_50.length);
        out.write(_jsp_string_51, 0, _jsp_string_51.length);
        out.write(_jsp_string_52, 0, _jsp_string_52.length);
        out.write(_jsp_string_53, 0, _jsp_string_53.length);
        out.write(_jsp_string_54, 0, _jsp_string_54.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_string_56, 0, _jsp_string_56.length);

        out.flush();
    }

    protected static final byte[] _jsp_string_1 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_string_2 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_string_3 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>Finder - Powered by Finder</title>\r\n");
    protected static final byte[] _jsp_string_4 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_string_5 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/admin/css/form.css\"/>\r\n");
    protected static final byte[] _jsp_string_6 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.7.2.min.js\"></script>\r\n");
    protected static final byte[] _jsp_string_7 = b("<script type=\"text/javascript\" src=\"?action=res&path=/admin/base.js\"></script>\r\n");
    protected static final byte[] _jsp_string_8 = b("<script type=\"text/javascript\">\r\n<!--\r\njQuery(function() {\r\n    var showHostList = function(userName, list) {\r\n");
    protected static final byte[] _jsp_string_9 = b("        var table = document.getElementById(\"host-table\");\r\n        jQuery(table).find(\"tr.item\").remove();\r\n");
    protected static final byte[] _jsp_string_10 = b("\r\n        if(list == null || list.length < 1) {\r\n            return;\r\n        }\r\n");
    protected static final byte[] _jsp_string_11 = b("\r\n        for(var i = 0; i < list.length; i++) {\r\n            var hostName = list[i];\r\n");
    protected static final byte[] _jsp_string_12 = b("            var tr = table.insertRow(-1);\r\n            var td1 = tr.insertCell(-1);\r\n");
    protected static final byte[] _jsp_string_13 = b("            var td2 = tr.insertCell(-1);\r\n\r\n            tr.className = \"item\";\r\n");
    protected static final byte[] _jsp_string_14 = b("            td1.innerHTML = hostName;\r\n            td2.innerHTML = \"<a class=\\\"btn delete\\\" href=\\\"javascript:void(0)\\\" userName=\\\"\" + userName + \"\\\" hostName=\\\"\" + hostName + \"\\\">删除</a>\";\r\n");
    protected static final byte[] _jsp_string_15 = b("        }\r\n        jQuery(\"#host-list\").show();\r\n    };\r\n\r\n    jQuery(\"input[name=query]\").click(function() {\r\n");
    protected static final byte[] _jsp_string_16 = b("        var userName = jQuery.trim(jQuery(\"input[name=userName]\").val());\r\n\r\n        if(userName.length < 1) {\r\n");
    protected static final byte[] _jsp_string_17 = b("            alert(\"请输入用户名！\");\r\n            return;\r\n        }\r\n\r\n        var src = jQuery(this);\r\n");
    protected static final byte[] _jsp_string_18 = b("        src.prop(\"disabled\", true);\r\n        src.prop(\"class\", \"button disabled\");\r\n");
    protected static final byte[] _jsp_string_19 = b("        jQuery.ajax({\r\n            \"type\": \"get\",\r\n            \"url\": \"?action=admin.policy.getHostPolicy&userName=\" + encodeURIComponent(userName),\r\n");
    protected static final byte[] _jsp_string_20 = b("            \"dataType\": \"json\",\r\n            \"error\": function() {\r\n                src.prop(\"disabled\", false);\r\n");
    protected static final byte[] _jsp_string_21 = b("                src.prop(\"class\", \"button\");\r\n                alert(\"系统错误，请稍后再试！\");\r\n");
    protected static final byte[] _jsp_string_22 = b("            },\r\n            \"success\": function(response) {\r\n                src.prop(\"disabled\", false);\r\n");
    protected static final byte[] _jsp_string_23 = b("                src.prop(\"class\", \"button\");\r\n                if(response.status != 200) {\r\n");
    protected static final byte[] _jsp_string_24 = b("                    alert(response.message);\r\n                    return;\r\n                }\r\n");
    protected static final byte[] _jsp_string_25 = b("\r\n                jQuery(\"#host-list\").show();\r\n                showHostList(userName, response.value);\r\n");
    protected static final byte[] _jsp_string_26 = b("            }\r\n        });\r\n    });\r\n\r\n    jQuery(\"input[name=flush]\").click(function() {\r\n");
    protected static final byte[] _jsp_string_27 = b("        var userName = jQuery.trim(jQuery(\"input[name=userName]\").val());\r\n\r\n        if(userName.length < 1) {\r\n");
    protected static final byte[] _jsp_string_28 = b("            return;\r\n        }\r\n\r\n        jQuery.ajax({\r\n            \"type\": \"get\",\r\n");
    protected static final byte[] _jsp_string_29 = b("            \"url\": \"?action=admin.policy.host.flush&userName=\" + encodeURIComponent(userName),\r\n");
    protected static final byte[] _jsp_string_30 = b("            \"dataType\": \"json\",\r\n            \"error\": function() {\r\n                alert(\"系统错误，请稍后再试！\");\r\n");
    protected static final byte[] _jsp_string_31 = b("            },\r\n            \"success\": function(response) {\r\n                if(response.status != 200) {\r\n");
    protected static final byte[] _jsp_string_32 = b("                    alert(response.message);\r\n                    return;\r\n                }\r\n");
    protected static final byte[] _jsp_string_33 = b("                alert(\"刷新成功，请重新查询！\");\r\n            }\r\n        });\r\n    });\r\n});\r\n");
    protected static final byte[] _jsp_string_34 = b("\r\njQuery(function() {\r\n    var remove = function(src) {\r\n        var userName = src.getAttribute(\"userName\");\r\n");
    protected static final byte[] _jsp_string_35 = b("        var hostName = src.getAttribute(\"hostName\");\r\n\r\n        if(hostName == null || hostName == undefined) {\r\n");
    protected static final byte[] _jsp_string_36 = b("            return;\r\n        }\r\n\r\n        jQuery.ajax({\r\n            \"type\": \"get\",\r\n");
    protected static final byte[] _jsp_string_37 = b("            \"url\": \"?action=admin.policy.host.remove&userName=\" + encodeURIComponent(userName) + \"&hostName=\" + encodeURIComponent(hostName),\r\n");
    protected static final byte[] _jsp_string_38 = b("            \"dataType\": \"json\",\r\n            \"error\": function() {\r\n                alert(\"系统错误，请稍后再试！\");\r\n");
    protected static final byte[] _jsp_string_39 = b("            },\r\n            \"success\": function(response) {\r\n                if(response.status != 200) {\r\n");
    protected static final byte[] _jsp_string_40 = b("                    alert(response.message);\r\n                    return;\r\n                }\r\n");
    protected static final byte[] _jsp_string_41 = b("                jQuery(src).closest(\"tr\").remove();\r\n            }\r\n        });\r\n");
    protected static final byte[] _jsp_string_42 = b("    };\r\n\r\n    jQuery(\"#host-table\").click(function(event) {\r\n        var src = (event.target || event.srcElement);\r\n");
    protected static final byte[] _jsp_string_43 = b("        var className = src.className;\r\n\r\n        if(className == null) {\r\n            return;\r\n");
    protected static final byte[] _jsp_string_44 = b("        }\r\n\r\n        if(className.indexOf(\"delete\") > -1) {\r\n            remove(src);\r\n");
    protected static final byte[] _jsp_string_45 = b("        }\r\n    });\r\n});\r\n//-->\r\n</script>\r\n</head>\r\n<body>\r\n<div class=\"menu-bar\">\r\n");
    protected static final byte[] _jsp_string_46 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.history.back();\"><span class=\"back\"></span>返回</a>\r\n");
    protected static final byte[] _jsp_string_47 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.location.reload();\"><span class=\"refresh\"></span>刷新</a>\r\n");
    protected static final byte[] _jsp_string_48 = b("    <span class=\"seperator\"></span>\r\n    <a class=\"button add\" href=\"javascript:void(0)\" onclick=\"window.location.href='?action=admin.user.host.edit';\"><span class=\"add\"></span>添加</a>\r\n");
    protected static final byte[] _jsp_string_49 = b("</div>\r\n<div class=\"form\">\r\n    <div style=\"margin: 10px 0px; font-size: 13px;\">请输入用户名查询该用户拥有的主机权限:</div>\r\n");
    protected static final byte[] _jsp_string_50 = b("    <div style=\"margin: 10px 0px;\">\r\n        <input name=\"userName\" type=\"text\" class=\"text w200\" placeholder=\"User Name\" value=\"\"/>\r\n");
    protected static final byte[] _jsp_string_51 = b("        <input name=\"query\" type=\"button\" class=\"button\" value=\"查询\"/>\r\n        <input name=\"flush\" type=\"button\" class=\"button\" value=\"刷新缓存\"/>\r\n");
    protected static final byte[] _jsp_string_52 = b("    </div>\r\n</div>\r\n<div id=\"host-list\" class=\"form\" style=\"display: none;\">\r\n    <table id=\"host-table\" class=\"list\">\r\n");
    protected static final byte[] _jsp_string_53 = b("        <tr class=\"head\">\r\n            <td>Host</td>\r\n            <td>操作</td>\r\n        </tr>\r\n");
    protected static final byte[] _jsp_string_54 = b("    </table>\r\n</div>\r\n<div id=\"pageContext\" style=\"display: none;\" contextPath=\"");
    protected static final byte[] _jsp_string_56 = b("\"></div>\r\n</body>\r\n</html>\r\n");

}
