/*
 * $RCSfile: UserListTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 */
package com.skin.finder.admin.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import java.util.List;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import com.skin.finder.security.User;


/**
 * <p>Title: UserListTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class UserListTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final UserListTemplate instance = new UserListTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();


    @SuppressWarnings("unchecked")
    List<User> userList = (List<User>)(request.getAttribute("userList"));

        out.write(_jsp_string_6, 0, _jsp_string_6.length);
        out.write(_jsp_string_7, 0, _jsp_string_7.length);
        out.write(_jsp_string_8, 0, _jsp_string_8.length);
        out.write(_jsp_string_9, 0, _jsp_string_9.length);
        out.write(_jsp_string_10, 0, _jsp_string_10.length);
        out.write(_jsp_string_11, 0, _jsp_string_11.length);
        out.write(_jsp_string_12, 0, _jsp_string_12.length);
        out.write(_jsp_string_13, 0, _jsp_string_13.length);
        out.write(_jsp_string_14, 0, _jsp_string_14.length);
        out.write(_jsp_string_15, 0, _jsp_string_15.length);
        out.write(_jsp_string_16, 0, _jsp_string_16.length);
        out.write(_jsp_string_17, 0, _jsp_string_17.length);
        out.write(_jsp_string_18, 0, _jsp_string_18.length);
        out.write(_jsp_string_19, 0, _jsp_string_19.length);
        out.write(_jsp_string_20, 0, _jsp_string_20.length);
        out.write(_jsp_string_21, 0, _jsp_string_21.length);
        out.write(_jsp_string_22, 0, _jsp_string_22.length);
        out.write(_jsp_string_23, 0, _jsp_string_23.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_string_25, 0, _jsp_string_25.length);
        out.write(_jsp_string_26, 0, _jsp_string_26.length);
        out.write(_jsp_string_27, 0, _jsp_string_27.length);
        out.write(_jsp_string_28, 0, _jsp_string_28.length);
        out.write(_jsp_string_29, 0, _jsp_string_29.length);

            if(userList != null && userList.size() > 0) {
                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

                for(User user : userList) {
        
        out.write(_jsp_string_31, 0, _jsp_string_31.length);
        this.write(out, (user.getUserName()));
        out.write(_jsp_string_33, 0, _jsp_string_33.length);
        this.write(out, (user.getUserName()));
        out.write(_jsp_string_35, 0, _jsp_string_35.length);
        this.write(out, (dateFormat.format(user.getCreateTime())));
        out.write(_jsp_string_37, 0, _jsp_string_37.length);
        this.write(out, (user.getUserName()));
        out.write(_jsp_string_39, 0, _jsp_string_39.length);
        this.write(out, (user.getUserName()));
        out.write(_jsp_string_41, 0, _jsp_string_41.length);

                }
            }
        
        out.write(_jsp_string_43, 0, _jsp_string_43.length);

        if(userList == null || userList.size() < 1) {
    
        out.write(_jsp_string_45, 0, _jsp_string_45.length);

        }
        else {
    
        out.write(_jsp_string_47, 0, _jsp_string_47.length);
        this.write(out, request.getAttribute("pageNum"));
        out.write(_jsp_string_49, 0, _jsp_string_49.length);
        this.write(out, request.getAttribute("pageSize"));
        out.write(_jsp_string_51, 0, _jsp_string_51.length);
        this.write(out, request.getAttribute("userCount"));
        out.write(_jsp_string_53, 0, _jsp_string_53.length);

        }
    
        out.write(_jsp_string_55, 0, _jsp_string_55.length);

        out.flush();
    }

    protected static final byte[] _jsp_string_6 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_string_7 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_string_8 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>Finder - Powered by Finder</title>\r\n");
    protected static final byte[] _jsp_string_9 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_string_10 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/admin/css/form.css\"/>\r\n");
    protected static final byte[] _jsp_string_11 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/finder/css/pagebar.css\"/>\r\n");
    protected static final byte[] _jsp_string_12 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.7.2.min.js\"></script>\r\n");
    protected static final byte[] _jsp_string_13 = b("<script type=\"text/javascript\" src=\"?action=res&path=/admin/base.js\"></script>\r\n");
    protected static final byte[] _jsp_string_14 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/scrollpage.js\"></script>\r\n");
    protected static final byte[] _jsp_string_15 = b("<script type=\"text/javascript\">\r\n<!--\r\njQuery(function() {\r\n    jQuery(\"table tr td a.delete\").click(function() {\r\n");
    protected static final byte[] _jsp_string_16 = b("        var userName = this.getAttribute(\"userName\");\r\n\r\n        if(!window.confirm(\"删除之后不可恢复，确定要删除 [\" + userName + \"] 吗？\")) {\r\n");
    protected static final byte[] _jsp_string_17 = b("            return;\r\n        }\r\n\r\n        jQuery.ajax({\r\n            \"type\": \"get\",\r\n");
    protected static final byte[] _jsp_string_18 = b("            \"url\": \"?action=admin.user.delete&userName=\" + encodeURIComponent(userName),\r\n");
    protected static final byte[] _jsp_string_19 = b("            \"dataType\": \"json\",\r\n            \"error\": function() {\r\n                alert(\"系统错误，请稍后再试！\");\r\n");
    protected static final byte[] _jsp_string_20 = b("            },\r\n            \"success\": function(response) {\r\n                if(response.status != 200) {\r\n");
    protected static final byte[] _jsp_string_21 = b("                    alert(response.message);\r\n                    return;\r\n                }\r\n");
    protected static final byte[] _jsp_string_22 = b("                window.location.reload();\r\n            }\r\n        });\r\n    });\r\n");
    protected static final byte[] _jsp_string_23 = b("});\r\n//-->\r\n</script>\r\n</head>\r\n<body contextPath=\"");
    protected static final byte[] _jsp_string_25 = b("\">\r\n<div class=\"menu-bar\">\r\n    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.history.back();\"><span class=\"back\"></span>返回</a>\r\n");
    protected static final byte[] _jsp_string_26 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.location.reload();\"><span class=\"refresh\"></span>刷新</a>\r\n");
    protected static final byte[] _jsp_string_27 = b("    <span class=\"seperator\"></span>\r\n</div>\r\n<div class=\"form\">\r\n    <div class=\"title\"><h4>用户管理</h4></div>\r\n");
    protected static final byte[] _jsp_string_28 = b("    <table id=\"host-table\" class=\"list\">\r\n        <tr class=\"head\">\r\n            <td>用户名</td>\r\n");
    protected static final byte[] _jsp_string_29 = b("            <td>注册时间</td>\r\n            <td>操作</td>\r\n        </tr>\r\n        ");
    protected static final byte[] _jsp_string_31 = b("        <tr userName=\"");
    protected static final byte[] _jsp_string_33 = b("\">\r\n            <td class=\"w200\">");
    protected static final byte[] _jsp_string_35 = b("</td>\r\n            <td class=\"w400\">");
    protected static final byte[] _jsp_string_37 = b("</td>\r\n            <td>\r\n                <a class=\"btn\" href=\"?action=admin.user.edit&userName=");
    protected static final byte[] _jsp_string_39 = b("\">修改</a>\r\n                <a class=\"btn delete\" href=\"javascript:void(0)\" userName=\"");
    protected static final byte[] _jsp_string_41 = b("\">刪除</a>\r\n            </td>\r\n        </tr>\r\n        ");
    protected static final byte[] _jsp_string_43 = b("    </table>\r\n    ");
    protected static final byte[] _jsp_string_45 = b("    <div style=\"margin: 10px 0px;\">无数据。</div>\r\n    ");
    protected static final byte[] _jsp_string_47 = b("    <div class=\"pagebar\">\r\n        <div name=\"scrollpage\" class=\"scrollpage\" theme=\"2\" pageNum=\"");
    protected static final byte[] _jsp_string_49 = b("\" pageSize=\"");
    protected static final byte[] _jsp_string_51 = b("\" count=\"");
    protected static final byte[] _jsp_string_53 = b("\" href=\"?action=admin.user.list&pageNum=%s\"></div>\r\n    </div>\r\n    ");
    protected static final byte[] _jsp_string_55 = b("</div>\r\n<div id=\"pageContext\" style=\"display: none;\"></div>\r\n</body>\r\n</html>\r\n");

}
