/*
 * $RCSfile: UserFilePolicyTemplate.java,v $
 * $Revision: 1.1 $
 *
 * JSP generated by JspCompiler-1.0.0
 */
package com.skin.finder.admin.servlet.template;

import java.io.IOException;
import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;



/**
 * <p>Title: UserFilePolicyTemplate</p>
 * <p>Description: </p>
 * @author JspKit
 * @version 1.0
 */
public class UserFilePolicyTemplate extends com.skin.finder.web.servlet.JspServlet {
    private static final long serialVersionUID = 1L;
    private static final UserFilePolicyTemplate instance = new UserFilePolicyTemplate();


    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    public static void execute(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        instance.service(request, response);
    }

    /**
     * @param request
     * @param response
     * @throws IOException
     * @throws ServletException
     */
    @Override
    public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html; charset=utf-8");
        OutputStream out = response.getOutputStream();

        out.write(_jsp_string_1, 0, _jsp_string_1.length);
        out.write(_jsp_string_2, 0, _jsp_string_2.length);
        out.write(_jsp_string_3, 0, _jsp_string_3.length);
        out.write(_jsp_string_4, 0, _jsp_string_4.length);
        out.write(_jsp_string_5, 0, _jsp_string_5.length);
        out.write(_jsp_string_6, 0, _jsp_string_6.length);
        out.write(_jsp_string_7, 0, _jsp_string_7.length);
        out.write(_jsp_string_8, 0, _jsp_string_8.length);
        out.write(_jsp_string_9, 0, _jsp_string_9.length);
        out.write(_jsp_string_10, 0, _jsp_string_10.length);
        out.write(_jsp_string_11, 0, _jsp_string_11.length);
        out.write(_jsp_string_12, 0, _jsp_string_12.length);
        out.write(_jsp_string_13, 0, _jsp_string_13.length);
        out.write(_jsp_string_14, 0, _jsp_string_14.length);
        out.write(_jsp_string_15, 0, _jsp_string_15.length);
        out.write(_jsp_string_16, 0, _jsp_string_16.length);
        out.write(_jsp_string_17, 0, _jsp_string_17.length);
        out.write(_jsp_string_18, 0, _jsp_string_18.length);
        out.write(_jsp_string_19, 0, _jsp_string_19.length);
        out.write(_jsp_string_20, 0, _jsp_string_20.length);
        out.write(_jsp_string_21, 0, _jsp_string_21.length);
        out.write(_jsp_string_22, 0, _jsp_string_22.length);
        out.write(_jsp_string_23, 0, _jsp_string_23.length);
        out.write(_jsp_string_24, 0, _jsp_string_24.length);
        out.write(_jsp_string_25, 0, _jsp_string_25.length);
        out.write(_jsp_string_26, 0, _jsp_string_26.length);
        out.write(_jsp_string_27, 0, _jsp_string_27.length);
        out.write(_jsp_string_28, 0, _jsp_string_28.length);
        out.write(_jsp_string_29, 0, _jsp_string_29.length);
        out.write(_jsp_string_30, 0, _jsp_string_30.length);
        out.write(_jsp_string_31, 0, _jsp_string_31.length);
        out.write(_jsp_string_32, 0, _jsp_string_32.length);
        out.write(_jsp_string_33, 0, _jsp_string_33.length);
        out.write(_jsp_string_34, 0, _jsp_string_34.length);
        out.write(_jsp_string_35, 0, _jsp_string_35.length);
        out.write(_jsp_string_36, 0, _jsp_string_36.length);
        out.write(_jsp_string_37, 0, _jsp_string_37.length);
        out.write(_jsp_string_38, 0, _jsp_string_38.length);
        out.write(_jsp_string_39, 0, _jsp_string_39.length);
        out.write(_jsp_string_40, 0, _jsp_string_40.length);
        out.write(_jsp_string_41, 0, _jsp_string_41.length);
        out.write(_jsp_string_42, 0, _jsp_string_42.length);
        out.write(_jsp_string_43, 0, _jsp_string_43.length);
        out.write(_jsp_string_44, 0, _jsp_string_44.length);
        out.write(_jsp_string_45, 0, _jsp_string_45.length);
        out.write(_jsp_string_46, 0, _jsp_string_46.length);
        out.write(_jsp_string_47, 0, _jsp_string_47.length);
        out.write(_jsp_string_48, 0, _jsp_string_48.length);
        out.write(_jsp_string_49, 0, _jsp_string_49.length);
        out.write(_jsp_string_50, 0, _jsp_string_50.length);
        out.write(_jsp_string_51, 0, _jsp_string_51.length);
        out.write(_jsp_string_52, 0, _jsp_string_52.length);
        out.write(_jsp_string_53, 0, _jsp_string_53.length);
        out.write(_jsp_string_54, 0, _jsp_string_54.length);
        out.write(_jsp_string_55, 0, _jsp_string_55.length);
        out.write(_jsp_string_56, 0, _jsp_string_56.length);
        out.write(_jsp_string_57, 0, _jsp_string_57.length);
        out.write(_jsp_string_58, 0, _jsp_string_58.length);
        out.write(_jsp_string_59, 0, _jsp_string_59.length);
        out.write(_jsp_string_60, 0, _jsp_string_60.length);
        out.write(_jsp_string_61, 0, _jsp_string_61.length);
        out.write(_jsp_string_62, 0, _jsp_string_62.length);
        out.write(_jsp_string_63, 0, _jsp_string_63.length);
        out.write(_jsp_string_64, 0, _jsp_string_64.length);
        out.write(_jsp_string_65, 0, _jsp_string_65.length);
        out.write(_jsp_string_66, 0, _jsp_string_66.length);
        out.write(_jsp_string_67, 0, _jsp_string_67.length);
        out.write(_jsp_string_68, 0, _jsp_string_68.length);
        out.write(_jsp_string_69, 0, _jsp_string_69.length);
        out.write(_jsp_string_70, 0, _jsp_string_70.length);
        out.write(_jsp_string_71, 0, _jsp_string_71.length);
        out.write(_jsp_string_72, 0, _jsp_string_72.length);
        out.write(_jsp_string_73, 0, _jsp_string_73.length);
        out.write(_jsp_string_74, 0, _jsp_string_74.length);
        out.write(_jsp_string_75, 0, _jsp_string_75.length);
        out.write(_jsp_string_76, 0, _jsp_string_76.length);
        out.write(_jsp_string_77, 0, _jsp_string_77.length);
        out.write(_jsp_string_78, 0, _jsp_string_78.length);
        out.write(_jsp_string_79, 0, _jsp_string_79.length);
        out.write(_jsp_string_80, 0, _jsp_string_80.length);
        out.write(_jsp_string_81, 0, _jsp_string_81.length);
        out.write(_jsp_string_82, 0, _jsp_string_82.length);
        out.write(_jsp_string_83, 0, _jsp_string_83.length);
        out.write(_jsp_string_84, 0, _jsp_string_84.length);
        out.write(_jsp_string_85, 0, _jsp_string_85.length);
        out.write(_jsp_string_86, 0, _jsp_string_86.length);
        out.write(_jsp_string_87, 0, _jsp_string_87.length);
        out.write(_jsp_string_88, 0, _jsp_string_88.length);
        out.write(_jsp_string_89, 0, _jsp_string_89.length);
        out.write(_jsp_string_90, 0, _jsp_string_90.length);
        out.write(_jsp_string_91, 0, _jsp_string_91.length);
        out.write(_jsp_string_92, 0, _jsp_string_92.length);
        out.write(_jsp_string_93, 0, _jsp_string_93.length);
        out.write(_jsp_string_94, 0, _jsp_string_94.length);
        out.write(_jsp_string_95, 0, _jsp_string_95.length);
        out.write(_jsp_string_96, 0, _jsp_string_96.length);
        out.write(_jsp_string_97, 0, _jsp_string_97.length);
        out.write(_jsp_string_98, 0, _jsp_string_98.length);
        out.write(_jsp_string_99, 0, _jsp_string_99.length);
        out.write(_jsp_string_100, 0, _jsp_string_100.length);
        out.write(_jsp_string_101, 0, _jsp_string_101.length);
        out.write(_jsp_string_102, 0, _jsp_string_102.length);
        out.write(_jsp_string_103, 0, _jsp_string_103.length);
        out.write(_jsp_string_104, 0, _jsp_string_104.length);
        out.write(_jsp_string_105, 0, _jsp_string_105.length);
        out.write(_jsp_string_106, 0, _jsp_string_106.length);
        out.write(_jsp_string_107, 0, _jsp_string_107.length);
        out.write(_jsp_string_108, 0, _jsp_string_108.length);
        out.write(_jsp_string_109, 0, _jsp_string_109.length);
        out.write(_jsp_string_110, 0, _jsp_string_110.length);
        out.write(_jsp_string_111, 0, _jsp_string_111.length);
        out.write(_jsp_string_112, 0, _jsp_string_112.length);
        out.write(_jsp_string_113, 0, _jsp_string_113.length);
        out.write(_jsp_string_114, 0, _jsp_string_114.length);
        out.write(_jsp_string_115, 0, _jsp_string_115.length);
        out.write(_jsp_string_116, 0, _jsp_string_116.length);
        out.write(_jsp_string_117, 0, _jsp_string_117.length);
        out.write(_jsp_string_118, 0, _jsp_string_118.length);
        out.write(_jsp_string_119, 0, _jsp_string_119.length);
        out.write(_jsp_string_120, 0, _jsp_string_120.length);
        out.write(_jsp_string_121, 0, _jsp_string_121.length);
        out.write(_jsp_string_122, 0, _jsp_string_122.length);
        out.write(_jsp_string_123, 0, _jsp_string_123.length);
        out.write(_jsp_string_124, 0, _jsp_string_124.length);
        out.write(_jsp_string_125, 0, _jsp_string_125.length);
        out.write(_jsp_string_126, 0, _jsp_string_126.length);
        out.write(_jsp_string_127, 0, _jsp_string_127.length);
        out.write(_jsp_string_128, 0, _jsp_string_128.length);
        out.write(_jsp_string_129, 0, _jsp_string_129.length);
        out.write(_jsp_string_130, 0, _jsp_string_130.length);
        out.write(_jsp_string_131, 0, _jsp_string_131.length);
        out.write(_jsp_string_132, 0, _jsp_string_132.length);
        out.write(_jsp_string_133, 0, _jsp_string_133.length);
        out.write(_jsp_string_134, 0, _jsp_string_134.length);
        out.write(_jsp_string_135, 0, _jsp_string_135.length);
        out.write(_jsp_string_136, 0, _jsp_string_136.length);
        out.write(_jsp_string_137, 0, _jsp_string_137.length);
        out.write(_jsp_string_138, 0, _jsp_string_138.length);
        out.write(_jsp_string_139, 0, _jsp_string_139.length);
        out.write(_jsp_string_140, 0, _jsp_string_140.length);
        out.write(_jsp_string_141, 0, _jsp_string_141.length);

    String[] hosts = (String[])(request.getAttribute("hosts"));

    if(hosts == null) {
        hosts = new String[0];
    }

        out.write(_jsp_string_143, 0, _jsp_string_143.length);
        out.write(_jsp_string_144, 0, _jsp_string_144.length);
        out.write(_jsp_string_145, 0, _jsp_string_145.length);

            for(String hostName : hosts) {
        
        out.write(_jsp_string_147, 0, _jsp_string_147.length);
        this.write(out, (hostName));
        out.write(_jsp_string_149, 0, _jsp_string_149.length);
        this.write(out, (hostName));
        out.write(_jsp_string_151, 0, _jsp_string_151.length);

            }
        
        out.write(_jsp_string_153, 0, _jsp_string_153.length);
        out.write(_jsp_string_154, 0, _jsp_string_154.length);
        out.write(_jsp_string_155, 0, _jsp_string_155.length);
        out.write(_jsp_string_156, 0, _jsp_string_156.length);
        out.write(_jsp_string_157, 0, _jsp_string_157.length);
        out.write(_jsp_string_158, 0, _jsp_string_158.length);
        out.write(_jsp_string_159, 0, _jsp_string_159.length);
        out.write(_jsp_string_160, 0, _jsp_string_160.length);
        out.write(_jsp_string_161, 0, _jsp_string_161.length);
        out.write(_jsp_string_162, 0, _jsp_string_162.length);
        out.write(_jsp_string_163, 0, _jsp_string_163.length);
        out.write(_jsp_string_164, 0, _jsp_string_164.length);
        out.write(_jsp_string_165, 0, _jsp_string_165.length);
        out.write(_jsp_string_166, 0, _jsp_string_166.length);
        out.write(_jsp_string_167, 0, _jsp_string_167.length);
        out.write(_jsp_string_168, 0, _jsp_string_168.length);
        out.write(_jsp_string_169, 0, _jsp_string_169.length);
        out.write(_jsp_string_170, 0, _jsp_string_170.length);
        out.write(_jsp_string_171, 0, _jsp_string_171.length);
        out.write(_jsp_string_172, 0, _jsp_string_172.length);
        out.write(_jsp_string_173, 0, _jsp_string_173.length);
        out.write(_jsp_string_174, 0, _jsp_string_174.length);
        out.write(_jsp_string_175, 0, _jsp_string_175.length);
        out.write(_jsp_string_176, 0, _jsp_string_176.length);
        out.write(_jsp_string_177, 0, _jsp_string_177.length);
        out.write(_jsp_string_178, 0, _jsp_string_178.length);
        this.write(out, request.getAttribute("contextPath"));
        out.write(_jsp_string_180, 0, _jsp_string_180.length);

        out.flush();
    }

    protected static final byte[] _jsp_string_1 = b("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
    protected static final byte[] _jsp_string_2 = b("<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n");
    protected static final byte[] _jsp_string_3 = b("<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>Finder - Powered by Finder</title>\r\n");
    protected static final byte[] _jsp_string_4 = b("<link rel=\"shortcut icon\" href=\"?action=res&path=/finder/images/favicon.png\"/>\r\n");
    protected static final byte[] _jsp_string_5 = b("<link rel=\"stylesheet\" type=\"text/css\" href=\"?action=res&path=/admin/css/form.css\"/>\r\n");
    protected static final byte[] _jsp_string_6 = b("<script type=\"text/javascript\" src=\"?action=res&path=/finder/jquery-1.7.2.min.js\"></script>\r\n");
    protected static final byte[] _jsp_string_7 = b("<script type=\"text/javascript\" src=\"?action=res&path=/admin/base.js\"></script>\r\n");
    protected static final byte[] _jsp_string_8 = b("<script type=\"text/javascript\">\r\n<!--\r\njQuery(function() {\r\n    var getOptions = function(name, list, value) {\r\n");
    protected static final byte[] _jsp_string_9 = b("        var b = [];\r\n        b[b.length] = \"<select name=\\\"\" + name + \"\\\" class=\\\"select\\\">\";\r\n");
    protected static final byte[] _jsp_string_10 = b("\r\n        for(var i = 0; i < list.length; i++) {\r\n            if(list[i] == value) {\r\n");
    protected static final byte[] _jsp_string_11 = b("                b[b.length] = \"<option value=\\\"\" + list[i] + \"\\\" selected=\\\"true\\\">\" + list[i] + \"</option>\";\r\n");
    protected static final byte[] _jsp_string_12 = b("            }\r\n            else {\r\n                b[b.length] = \"<option value=\\\"\" + list[i] + \"\\\">\" + list[i] + \"</option>\";\r\n");
    protected static final byte[] _jsp_string_13 = b("            }\r\n        }\r\n        b[b.length] = \"</select>\";\r\n        return b.join(\"\");\r\n");
    protected static final byte[] _jsp_string_14 = b("    };\r\n\r\n    var showPermissionList = function(userName, hostName, bean) {\r\n        var table = document.getElementById(\"permission-table\");\r\n");
    protected static final byte[] _jsp_string_15 = b("        jQuery(table).find(\"tr.item\").remove();\r\n\r\n        var workspaces = bean.workspaces;\r\n");
    protected static final byte[] _jsp_string_16 = b("        var permissions = bean.permissions;\r\n\r\n        table.setAttribute(\"hostName\", hostName);\r\n");
    protected static final byte[] _jsp_string_17 = b("        table.setAttribute(\"workspaces\", workspaces.join(\",\"));\r\n\r\n        if(permissions == null || permissions.length < 1) {\r\n");
    protected static final byte[] _jsp_string_18 = b("            return;\r\n        }\r\n\r\n        var compare = function(s1, s2) {\r\n            if(s1 == s2) {\r\n");
    protected static final byte[] _jsp_string_19 = b("                return 0;\r\n            }\r\n\r\n            if(s1 > s2) {\r\n                return 1;\r\n");
    protected static final byte[] _jsp_string_20 = b("            }\r\n            else {\r\n                return -1;\r\n            }\r\n        };\r\n");
    protected static final byte[] _jsp_string_21 = b("\r\n        var comparator = function(p1, p2) {\r\n            var v = compare(p1.workspace, p2.workspace);\r\n");
    protected static final byte[] _jsp_string_22 = b("\r\n            if(v == 0) {\r\n                return compare(p1.action, p2.action);\r\n");
    protected static final byte[] _jsp_string_23 = b("            }\r\n            return v;\r\n        };\r\n\r\n        permissions.sort(comparator);\r\n");
    protected static final byte[] _jsp_string_24 = b("\r\n        var colors = {\r\n            \"index\": 0,\r\n            \"values\": [\"#ffffff\", \"#f4f8c9\", \"#c2defb\", \"#fdc4c4\"],\r\n");
    protected static final byte[] _jsp_string_25 = b("            \"next\": function() {\r\n                if(this.index >= this.values.length) {\r\n");
    protected static final byte[] _jsp_string_26 = b("                    this.index = 0;\r\n                }\r\n                return this.values[this.index++];\r\n");
    protected static final byte[] _jsp_string_27 = b("            }\r\n        };\r\n\r\n        var current = null;\r\n        var bgcolor = colors.next();\r\n");
    protected static final byte[] _jsp_string_28 = b("        var actions = [\"read\", \"write\", \"delete\", \"download\"];\r\n\r\n        for(var i = 0; i < permissions.length; i++) {\r\n");
    protected static final byte[] _jsp_string_29 = b("            var permission = permissions[i];\r\n            var tr = table.insertRow(-1);\r\n");
    protected static final byte[] _jsp_string_30 = b("            var td1 = tr.insertCell(-1);\r\n            var td2 = tr.insertCell(-1);\r\n");
    protected static final byte[] _jsp_string_31 = b("            var td3 = tr.insertCell(-1);\r\n            var td4 = tr.insertCell(-1);\r\n");
    protected static final byte[] _jsp_string_32 = b("\r\n            if(current != permission.workspace) {\r\n                bgcolor = colors.next();\r\n");
    protected static final byte[] _jsp_string_33 = b("                current = permission.workspace;\r\n            }\r\n\r\n            tr.className = \"item\";\r\n");
    protected static final byte[] _jsp_string_34 = b("            td1.style.backgroundColor = bgcolor;\r\n            td1.innerHTML = getOptions(\"workspace\", workspaces, permission.workspace);\r\n");
    protected static final byte[] _jsp_string_35 = b("            td2.innerHTML = getOptions(\"action\", actions, permission.action);\r\n            td3.innerHTML = \"<input name=\\\"pattern\\\" type=\\\"text\\\" class=\\\"text\\\" style=\\\"width: 80%; box-sizing: border-box;\\\" value=\\\"\" + permission.pattern + \"\\\"/>\";\r\n");
    protected static final byte[] _jsp_string_36 = b("            td4.innerHTML = \"<a class=\\\"btn delete\\\" href=\\\"javascript:void(0)\\\" userName=\\\"\" + userName + \"\\\" hostName=\\\"\" + hostName + \"\\\" onclick=\\\"jQuery(this).closest('tr').remove();\\\">删除</a>\";\r\n");
    protected static final byte[] _jsp_string_37 = b("        }\r\n    };\r\n\r\n    jQuery(\"#add-btn\").click(function() {\r\n        var table = document.getElementById(\"permission-table\");\r\n");
    protected static final byte[] _jsp_string_38 = b("        var tr = table.insertRow(-1);\r\n        var td1 = tr.insertCell(-1);\r\n        var td2 = tr.insertCell(-1);\r\n");
    protected static final byte[] _jsp_string_39 = b("        var td3 = tr.insertCell(-1);\r\n        var td4 = tr.insertCell(-1);\r\n        var workspaces = table.getAttribute(\"workspaces\").split(\",\");\r\n");
    protected static final byte[] _jsp_string_40 = b("        var actions = [\"read\", \"write\", \"delete\", \"download\"];\r\n\r\n        tr.className = \"item\";\r\n");
    protected static final byte[] _jsp_string_41 = b("        td1.innerHTML = getOptions(\"workspace\", workspaces, \"\");\r\n        td2.innerHTML = getOptions(\"action\", actions, \"read\");\r\n");
    protected static final byte[] _jsp_string_42 = b("        td3.innerHTML = \"<input name=\\\"pattern\\\" type=\\\"text\\\" class=\\\"text\\\" style=\\\"width: 80%; box-sizing: border-box;\\\" value=\\\"/**\\\"/>\";\r\n");
    protected static final byte[] _jsp_string_43 = b("        td4.innerHTML = \"<a class=\\\"btn delete\\\" href=\\\"javascript:void(0)\\\" onclick=\\\"jQuery(this).closest('tr').remove();\\\">删除</a>\";\r\n");
    protected static final byte[] _jsp_string_44 = b("    });\r\n\r\n    jQuery(\"input[name=query]\").click(function() {\r\n        var userName = jQuery.trim(jQuery(\"input[name=userName]\").val());\r\n");
    protected static final byte[] _jsp_string_45 = b("        var hostName = jQuery.trim(jQuery(\"select[name=hostName]\").val());\r\n\r\n        if(userName.length < 1) {\r\n");
    protected static final byte[] _jsp_string_46 = b("            alert(\"userName 不能为空！\");\r\n            return;\r\n        }\r\n\r\n        if(hostName.length < 1) {\r\n");
    protected static final byte[] _jsp_string_47 = b("            alert(\"hostName 不能为空！\");\r\n            return;\r\n        }\r\n\r\n        var src = jQuery(this);\r\n");
    protected static final byte[] _jsp_string_48 = b("        src.prop(\"disabled\", true);\r\n        src.prop(\"class\", \"button disabled\");\r\n");
    protected static final byte[] _jsp_string_49 = b("\r\n        var params = [];\r\n        params[params.length] = \"host=\" + encodeURIComponent(hostName);\r\n");
    protected static final byte[] _jsp_string_50 = b("        params[params.length] = \"userName=\" + encodeURIComponent(userName);\r\n\r\n        jQuery.ajax({\r\n");
    protected static final byte[] _jsp_string_51 = b("            \"type\": \"get\",\r\n            \"url\": \"?action=admin.policy.getFilePolicy&\" + params.join(\"&\"),\r\n");
    protected static final byte[] _jsp_string_52 = b("            \"dataType\": \"json\",\r\n            \"error\": function() {\r\n                src.prop(\"disabled\", false);\r\n");
    protected static final byte[] _jsp_string_53 = b("                src.prop(\"class\", \"button\");\r\n                alert(\"系统错误，请稍后再试！\");\r\n");
    protected static final byte[] _jsp_string_54 = b("            },\r\n            \"success\": function(response) {\r\n                src.prop(\"disabled\", false);\r\n");
    protected static final byte[] _jsp_string_55 = b("                src.prop(\"class\", \"button\");\r\n\r\n                if(response.status != 200) {\r\n");
    protected static final byte[] _jsp_string_56 = b("                    alert(response.message);\r\n                    return;\r\n                }\r\n");
    protected static final byte[] _jsp_string_57 = b("                jQuery(\"#permission-panel\").show();\r\n                jQuery(\"#advance-panel\").hide();\r\n");
    protected static final byte[] _jsp_string_58 = b("                showPermissionList(userName, hostName, response.value);\r\n            }\r\n");
    protected static final byte[] _jsp_string_59 = b("        });\r\n    });\r\n\r\n    jQuery(\"input[name=flush]\").click(function() {\r\n        var userName = jQuery.trim(jQuery(\"input[name=userName]\").val());\r\n");
    protected static final byte[] _jsp_string_60 = b("        var hostName = jQuery.trim(jQuery(\"select[name=hostName]\").val());\r\n\r\n        if(userName.length < 1) {\r\n");
    protected static final byte[] _jsp_string_61 = b("            alert(\"userName 不能为空！\");\r\n            return;\r\n        }\r\n\r\n        if(hostName.length < 1) {\r\n");
    protected static final byte[] _jsp_string_62 = b("            alert(\"hostName 不能为空！\");\r\n            return;\r\n        }\r\n\r\n        var src = jQuery(this);\r\n");
    protected static final byte[] _jsp_string_63 = b("        src.prop(\"disabled\", true);\r\n        src.prop(\"class\", \"button disabled\");\r\n");
    protected static final byte[] _jsp_string_64 = b("\r\n        var params = [];\r\n        params[params.length] = \"host=\" + encodeURIComponent(hostName);\r\n");
    protected static final byte[] _jsp_string_65 = b("        params[params.length] = \"userName=\" + encodeURIComponent(userName);\r\n\r\n        jQuery.ajax({\r\n");
    protected static final byte[] _jsp_string_66 = b("            \"type\": \"get\",\r\n            \"url\": \"?action=admin.policy.file.flush&\" + params.join(\"&\"),\r\n");
    protected static final byte[] _jsp_string_67 = b("            \"dataType\": \"json\",\r\n            \"error\": function() {\r\n                src.prop(\"disabled\", false);\r\n");
    protected static final byte[] _jsp_string_68 = b("                src.prop(\"class\", \"button\");\r\n                alert(\"系统错误，请稍后再试！\");\r\n");
    protected static final byte[] _jsp_string_69 = b("            },\r\n            \"success\": function(response) {\r\n                src.prop(\"disabled\", false);\r\n");
    protected static final byte[] _jsp_string_70 = b("                src.prop(\"class\", \"button\");\r\n                if(response.status != 200) {\r\n");
    protected static final byte[] _jsp_string_71 = b("                    alert(response.message);\r\n                    return;\r\n                }\r\n");
    protected static final byte[] _jsp_string_72 = b("                alert(\"刷新成功，请重新查询！\");\r\n            }\r\n        });\r\n    });\r\n});\r\n");
    protected static final byte[] _jsp_string_73 = b("\r\njQuery(function() {\r\n    var getUserPermission = function() {\r\n        var context = {};\r\n");
    protected static final byte[] _jsp_string_74 = b("\r\n        jQuery(\"#permission-table tr\").each(function() {\r\n            var workspace = jQuery.trim(jQuery(this).find(\"select[name=workspace]\").val());\r\n");
    protected static final byte[] _jsp_string_75 = b("            var pattern = jQuery.trim(jQuery(this).find(\"input[name=pattern]\").val());\r\n");
    protected static final byte[] _jsp_string_76 = b("            var action = jQuery.trim(jQuery(this).find(\"select[name=action]\").val());\r\n");
    protected static final byte[] _jsp_string_77 = b("\r\n            if(workspace.length < 1 || pattern.length < 1) {\r\n                return;\r\n");
    protected static final byte[] _jsp_string_78 = b("            }\r\n\r\n            if(pattern.charAt(0) == \"!\") {\r\n                if(pattern.length < 2 || pattern.charAt(1) != \"/\") {\r\n");
    protected static final byte[] _jsp_string_79 = b("                    return;\r\n                }\r\n            }\r\n            else if(pattern.charAt(0) != \"/\") {\r\n");
    protected static final byte[] _jsp_string_80 = b("                return;\r\n            }\r\n\r\n            var key = action + \"@\" + workspace;\r\n");
    protected static final byte[] _jsp_string_81 = b("            var permission = context[key];\r\n\r\n            if(permission == null) {\r\n");
    protected static final byte[] _jsp_string_82 = b("                permission = context[key] = {\"workspace\": workspace, \"action\": action, \"includes\": []};\r\n");
    protected static final byte[] _jsp_string_83 = b("            }\r\n\r\n            var includes = permission.includes;\r\n            includes[includes.length] = pattern;\r\n");
    protected static final byte[] _jsp_string_84 = b("        });\r\n        return context;\r\n    };\r\n\r\n    var getWorkspaceList = function(context) {\r\n");
    protected static final byte[] _jsp_string_85 = b("        var map = {};\r\n        var list = [];\r\n\r\n        for(var key in context) {\r\n");
    protected static final byte[] _jsp_string_86 = b("            var permission = context[key];\r\n            var workspace = permission.workspace;\r\n");
    protected static final byte[] _jsp_string_87 = b("            map[workspace] = workspace;\r\n        }\r\n\r\n        for(var name in map) {\r\n");
    protected static final byte[] _jsp_string_88 = b("            list[list.length] = name;\r\n        }\r\n        return list;\r\n    };\r\n");
    protected static final byte[] _jsp_string_89 = b("\r\n    var getContent = function() {\r\n        var userPermission = getUserPermission();\r\n");
    protected static final byte[] _jsp_string_90 = b("        var workspaceList = getWorkspaceList(userPermission);\r\n\r\n        var b = [];\r\n");
    protected static final byte[] _jsp_string_91 = b("        b[b.length] = \"grant read on localhost@@ {\\r\\n\";\r\n\r\n        for(var i = 0; i < workspaceList.length; i++) {\r\n");
    protected static final byte[] _jsp_string_92 = b("            b[b.length] = \"    include \" + workspaceList[i] + \"\\r\\n\";\r\n        }\r\n");
    protected static final byte[] _jsp_string_93 = b("        b[b.length] = \"}\\r\\n\\r\\n\";\r\n\r\n        for(var key in userPermission) {\r\n");
    protected static final byte[] _jsp_string_94 = b("            var permission = userPermission[key];\r\n            var workspace = permission.workspace;\r\n");
    protected static final byte[] _jsp_string_95 = b("            var action = permission.action;\r\n            var includes = permission.includes;\r\n");
    protected static final byte[] _jsp_string_96 = b("            b[b.length] = \"grant \" + action + \" on localhost@\" + workspace + \" {\\r\\n\";\r\n");
    protected static final byte[] _jsp_string_97 = b("\r\n            for(var i = 0; i < includes.length; i++) {\r\n                var pattern = jQuery.trim(includes[i]);\r\n");
    protected static final byte[] _jsp_string_98 = b("\r\n                if(pattern.length < 1) {\r\n                    continue;\r\n                }\r\n");
    protected static final byte[] _jsp_string_99 = b("\r\n                if(pattern.charAt(0) == \"!\") {\r\n                    b[b.length] = \"    exclude \" + pattern.substring(1) + \"\\r\\n\";\r\n");
    protected static final byte[] _jsp_string_100 = b("                }\r\n                else {\r\n                    b[b.length] = \"    include \" + pattern + \"\\r\\n\";\r\n");
    protected static final byte[] _jsp_string_101 = b("                }\r\n            }\r\n            b[b.length] = \"}\\r\\n\\r\\n\";\r\n        }\r\n");
    protected static final byte[] _jsp_string_102 = b("        return b.join(\"\");\r\n    };\r\n\r\n    jQuery(\"input[name=submit]\").click(function(event) {\r\n");
    protected static final byte[] _jsp_string_103 = b("        var userName = jQuery.trim(jQuery(\"input[name=userName]\").val());\r\n        var hostName = jQuery.trim(jQuery(\"#permission-table\").attr(\"hostName\"));\r\n");
    protected static final byte[] _jsp_string_104 = b("        var content = getContent();\r\n\r\n        if(userName.length < 1) {\r\n            alert(\"userName 不能为空！\");\r\n");
    protected static final byte[] _jsp_string_105 = b("            return;\r\n        }\r\n\r\n        if(hostName.length < 1) {\r\n            alert(\"hostName 不能为空！\");\r\n");
    protected static final byte[] _jsp_string_106 = b("            return;\r\n        }\r\n\r\n        var params = [];\r\n        params[params.length] = \"userName=\" + encodeURIComponent(userName);\r\n");
    protected static final byte[] _jsp_string_107 = b("        params[params.length] = \"content=\" + encodeURIComponent(content);\r\n\r\n        jQuery.ajax({\r\n");
    protected static final byte[] _jsp_string_108 = b("            \"type\": \"post\",\r\n            \"url\": \"?action=admin.policy.file.save&host=\" + encodeURIComponent(hostName),\r\n");
    protected static final byte[] _jsp_string_109 = b("            \"dataType\": \"json\",\r\n            \"data\": params.join(\"&\"),\r\n            \"error\": function() {\r\n");
    protected static final byte[] _jsp_string_110 = b("                alert(\"系统错误，请稍后再试！\");\r\n            },\r\n            \"success\": function(response) {\r\n");
    protected static final byte[] _jsp_string_111 = b("                if(response.status != 200) {\r\n                    alert(response.message);\r\n");
    protected static final byte[] _jsp_string_112 = b("                    return;\r\n                }\r\n                alert(\"保存成功，请重新查询！\");\r\n");
    protected static final byte[] _jsp_string_113 = b("            }\r\n        });\r\n    });\r\n\r\n    jQuery(\"input[name=test]\").click(function(event) {\r\n");
    protected static final byte[] _jsp_string_114 = b("        var userName = jQuery.trim(jQuery(\"input[name=userName]\").val());\r\n        var hostName = jQuery.trim(jQuery(\"select[name=hostName]\").val());\r\n");
    protected static final byte[] _jsp_string_115 = b("        var path = jQuery.trim(jQuery(\"input[name=path]\").val());\r\n\r\n        if(userName.length < 1) {\r\n");
    protected static final byte[] _jsp_string_116 = b("            alert(\"userName 不能为空！\");\r\n            return;\r\n        }\r\n\r\n        if(hostName.length < 1) {\r\n");
    protected static final byte[] _jsp_string_117 = b("            alert(\"hostName 不能为空！\");\r\n            return;\r\n        }\r\n\r\n        if(path.length < 1) {\r\n");
    protected static final byte[] _jsp_string_118 = b("            alert(\"测试路径不能为空！\");\r\n            return;\r\n        }\r\n\r\n        var params = [];\r\n");
    protected static final byte[] _jsp_string_119 = b("        params[params.length] = \"userName=\" + encodeURIComponent(userName);\r\n        params[params.length] = \"path=\" + encodeURIComponent(path);\r\n");
    protected static final byte[] _jsp_string_120 = b("\r\n        jQuery.ajax({\r\n            \"type\": \"post\",\r\n            \"url\": \"?action=admin.policy.file.test&host=\" + encodeURIComponent(hostName),\r\n");
    protected static final byte[] _jsp_string_121 = b("            \"dataType\": \"json\",\r\n            \"data\": params.join(\"&\"),\r\n            \"error\": function() {\r\n");
    protected static final byte[] _jsp_string_122 = b("                alert(\"系统错误，请稍后再试！\");\r\n            },\r\n            \"success\": function(response) {\r\n");
    protected static final byte[] _jsp_string_123 = b("                alert(response.value);\r\n            }\r\n        });\r\n    });\r\n\r\n    jQuery(\"input[name=edit-mode-btn]\").click(function() {\r\n");
    protected static final byte[] _jsp_string_124 = b("        var src = jQuery(this);\r\n\r\n        if(src.attr(\"edit-mode\") == \"1\") {\r\n            jQuery(\"#permission-panel\").hide();\r\n");
    protected static final byte[] _jsp_string_125 = b("            jQuery(\"#advance-panel\").show();\r\n        }\r\n        else {\r\n            src.attr(\"edit-mode\", \"0\");\r\n");
    protected static final byte[] _jsp_string_126 = b("            jQuery(\"#permission-panel\").show();\r\n            jQuery(\"#advance-panel\").hide();\r\n");
    protected static final byte[] _jsp_string_127 = b("        }\r\n    });\r\n\r\n    jQuery(\"input[name=advance-submit]\").click(function(event) {\r\n");
    protected static final byte[] _jsp_string_128 = b("        var userName = jQuery.trim(jQuery(\"input[name=userName]\").val());\r\n        var hostName = jQuery.trim(jQuery(\"select[name=hostName]\").val());\r\n");
    protected static final byte[] _jsp_string_129 = b("        var content = jQuery(\"textarea[name=content]\").val();\r\n\r\n        if(userName.length < 1) {\r\n");
    protected static final byte[] _jsp_string_130 = b("            alert(\"userName 不能为空！\");\r\n            return;\r\n        }\r\n\r\n        if(hostName.length < 1) {\r\n");
    protected static final byte[] _jsp_string_131 = b("            alert(\"hostName 不能为空！\");\r\n            return;\r\n        }\r\n\r\n        var params = [];\r\n");
    protected static final byte[] _jsp_string_132 = b("        params[params.length] = \"userName=\" + encodeURIComponent(userName);\r\n        params[params.length] = \"content=\" + encodeURIComponent(content);\r\n");
    protected static final byte[] _jsp_string_133 = b("\r\n        jQuery.ajax({\r\n            \"type\": \"post\",\r\n            \"url\": \"?action=admin.policy.file.save&host=\" + encodeURIComponent(hostName),\r\n");
    protected static final byte[] _jsp_string_134 = b("            \"dataType\": \"json\",\r\n            \"data\": params.join(\"&\"),\r\n            \"error\": function() {\r\n");
    protected static final byte[] _jsp_string_135 = b("                alert(\"系统错误，请稍后再试！\");\r\n            },\r\n            \"success\": function(response) {\r\n");
    protected static final byte[] _jsp_string_136 = b("                if(response.status != 200) {\r\n                    alert(response.message);\r\n");
    protected static final byte[] _jsp_string_137 = b("                    return;\r\n                }\r\n                alert(\"保存成功，请重新查询！\");\r\n");
    protected static final byte[] _jsp_string_138 = b("            }\r\n        });\r\n    });\r\n});\r\n//-->\r\n</script>\r\n</head>\r\n<body>\r\n<div class=\"menu-bar\">\r\n");
    protected static final byte[] _jsp_string_139 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.history.back();\"><span class=\"back\"></span>返回</a>\r\n");
    protected static final byte[] _jsp_string_140 = b("    <a class=\"button\" href=\"javascript:void(0)\" onclick=\"window.location.reload();\"><span class=\"refresh\"></span>刷新</a>\r\n");
    protected static final byte[] _jsp_string_141 = b("    <span class=\"seperator\"></span>\r\n</div>\r\n");
    protected static final byte[] _jsp_string_143 = b("<div class=\"form\">\r\n    <div style=\"margin: 10px 0px; font-size: 13px;\">请输入用户名查询该用户拥有的文件权限:</div>\r\n");
    protected static final byte[] _jsp_string_144 = b("    <div style=\"margin: 10px 0px;\">\r\n        <input name=\"userName\" type=\"text\" class=\"text w200\" title=\"用户名\" placeholder=\"user name\" value=\"\"/>\r\n");
    protected static final byte[] _jsp_string_145 = b("        <select name=\"hostName\" type=\"text\" class=\"select w200\" title=\"主机\">\r\n        ");
    protected static final byte[] _jsp_string_147 = b("            <option value=\"");
    protected static final byte[] _jsp_string_149 = b("\">");
    protected static final byte[] _jsp_string_151 = b("</option>\r\n        ");
    protected static final byte[] _jsp_string_153 = b("        </select>\r\n        <input name=\"query\" type=\"button\" class=\"button\" value=\"查询\"/>\r\n");
    protected static final byte[] _jsp_string_154 = b("        <input name=\"flush\" type=\"button\" class=\"button\" value=\"刷新缓存\"/>\r\n    </div>\r\n");
    protected static final byte[] _jsp_string_155 = b("</div>\r\n<div id=\"permission-panel\" class=\"form\" style=\"display: none;\">\r\n    <div class=\"title\"><h4>操作说明</h4></div>\r\n");
    protected static final byte[] _jsp_string_156 = b("    <ul class=\"tips\">\r\n        <li>\r\n            <div style=\"color: #ff0000;\">路径匹配必须以/或者!/开头，支持通配符，遵循ANT路径匹配规则;</div>\r\n");
    protected static final byte[] _jsp_string_157 = b("<pre style=\"padding: 8px 0px; width: 80%; box-sizing: border-box; line-height: 20px; font-size: 14px;\">\r\n");
    protected static final byte[] _jsp_string_158 = b("!    排除, 只能出现在开头\r\n?    匹配任何单字符\r\n*    匹配0或者任意数量的字符\r\n**   匹配0或者更多的目录\r\n</pre>\r\n        </li>\r\n");
    protected static final byte[] _jsp_string_159 = b("    </ul>\r\n    <div style=\"margin: 10px 0px;\">\r\n        <table id=\"permission-table\" class=\"list\">\r\n");
    protected static final byte[] _jsp_string_160 = b("            <tr class=\"head\">\r\n                <td class=\"w200\">工作空间</td>\r\n                <td class=\"w200\">操作权限</td>\r\n");
    protected static final byte[] _jsp_string_161 = b("                <td class=\"w300\">路径匹配</td>\r\n                <td>操作</td>\r\n            </tr>\r\n");
    protected static final byte[] _jsp_string_162 = b("        </table>\r\n        <div style=\"margin: 10px 0px 10px 210px;\">\r\n            <a id=\"add-btn\" class=\"add-row\" href=\"javascript:void(0)\">添加权限</a>\r\n");
    protected static final byte[] _jsp_string_163 = b("        </div>\r\n    </div>\r\n    <!-- div style=\"margin: 10px 0px;\">\r\n        测试路径：<input name=\"path\" type=\"text\" class=\"text w400\" title=\"测试路径\" placeholder=\"\" value=\"\"/>\r\n");
    protected static final byte[] _jsp_string_164 = b("        <input name=\"test\" type=\"button\" class=\"button\" value=\"测试\"/>\r\n    </div -->\r\n");
    protected static final byte[] _jsp_string_165 = b("    <div style=\"margin: 10px 0px;\">\r\n        <input name=\"submit\" type=\"button\" class=\"button\" value=\"保存\"/>\r\n");
    protected static final byte[] _jsp_string_166 = b("        <input name=\"edit-mode-btn\" type=\"button\" class=\"button\" edit-mode=\"1\" value=\"高级权限设置\"/>\r\n");
    protected static final byte[] _jsp_string_167 = b("    </div>\r\n</div>\r\n<div id=\"advance-panel\" class=\"form\" style=\"display: none;\">\r\n");
    protected static final byte[] _jsp_string_168 = b("        <div class=\"title\"><h4>操作说明</h4></div>\r\n    <ul class=\"tips\">\r\n        <li>\r\n");
    protected static final byte[] _jsp_string_169 = b("            <div style=\"color: #ff0000;\">路径匹配必须以/开头，支持通配符，遵循ANT路径匹配规则;</div>\r\n<pre style=\"padding: 8px 0px; width: 80%; box-sizing: border-box; line-height: 20px; font-size: 14px;\">\r\n");
    protected static final byte[] _jsp_string_170 = b("1. grant read on localhost, 此处只能且必须是localhost;\r\n2. 两个@表示用户能看到的工作空间;\r\n3. include表示包含某个目录或者文件;\r\n");
    protected static final byte[] _jsp_string_171 = b("4. exclude表示排除某个目录或者文件;\r\n</pre>\r\n        </li>\r\n    </ul>\r\n    <div style=\"margin: 10px 0px;\">\r\n");
    protected static final byte[] _jsp_string_172 = b("        <textarea name=\"content\" style=\"width: 800px; height: 200px; outline: none; resize: none; background-color: #000000; color: #999999;\">\r\n");
    protected static final byte[] _jsp_string_173 = b("# 这只是一个示例, 请从外部编辑好之后粘贴到此处并保存\r\ngrant read on localhost@@ {\r\n    include finder.webapp\r\n");
    protected static final byte[] _jsp_string_174 = b("    include server1.mp3\r\n}\r\n\r\ngrant read on localhost@finder.webapp {\r\n    include /**\r\n");
    protected static final byte[] _jsp_string_175 = b("}\r\n\r\ngrant read on localhost@server1.mp3 {\r\n    include /**\r\n    exclude /test\r\n");
    protected static final byte[] _jsp_string_176 = b("}\r\n</textarea>\r\n    </div>\r\n    <div style=\"margin: 10px 0px;\">\r\n        <input name=\"advance-submit\" type=\"button\" class=\"button\" value=\"保存\"/>\r\n");
    protected static final byte[] _jsp_string_177 = b("        <input name=\"edit-mode-btn\" type=\"button\" class=\"button\" edit-mode=\"0\" value=\"一般权限设置\"/>\r\n");
    protected static final byte[] _jsp_string_178 = b("    </div>\r\n</div>\r\n<div id=\"pageContext\" style=\"display: none;\" contextPath=\"");
    protected static final byte[] _jsp_string_180 = b("\"></div>\r\n</body>\r\n</html>\r\n");

}
